"""Type stubs for molrs Python bindings.

Hand-maintained. Keep in sync with the PyO3 source in `molrs-python/src/**.rs`
on every PR that touches `#[pyfunction]` or `#[pyclass]`. The docs CI runs a
freshness guard that asserts every export in `src/lib.rs` is declared here.
"""

from typing import Any, List, Optional, Sequence, Tuple, Union, overload
import numpy as np
import numpy.typing as npt

# Type aliases — `F = f64` is invariant in molrs-core; Python side must match.
ArrayF = npt.NDArray[np.float64]
ArrayBool = npt.NDArray[np.bool_]
ArrayU8 = npt.NDArray[np.uint8]
ArrayU32 = npt.NDArray[np.uint32]
ArrayI64 = npt.NDArray[np.int64]

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class BlockDtypeError(TypeError):
    """Raised by ``Block.insert`` for a non-numpy-representable column.

    The Rust Store holds only float / int / bool / str columns. Object-dtype,
    None-bearing, and ragged/mixed arrays are rejected fail-fast; the message
    names the column and the detected dtype. Subclasses ``TypeError``.
    """

# ---------------------------------------------------------------------------
# Simulation box
# ---------------------------------------------------------------------------

class Box:
    """Simulation box with periodic boundary conditions."""

    def __init__(
        self,
        h: ArrayF,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> None: ...
    @staticmethod
    def cube(
        a: float,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> Box: ...
    @staticmethod
    def ortho(
        lengths: ArrayF,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> Box: ...
    def volume(self) -> float: ...
    def lattice(self, index: int) -> ArrayF: ...
    @property
    def h(self) -> ArrayF: ...
    @property
    def origin(self) -> ArrayF: ...
    @property
    def pbc(self) -> ArrayBool: ...
    def lengths(self) -> ArrayF: ...
    def to_frac(self, xyz: ArrayF) -> ArrayF: ...
    def to_cart(self, xyzs: ArrayF) -> ArrayF: ...
    def wrap(self, xyzu: ArrayF) -> ArrayF: ...
    def delta(
        self, xyzu1: ArrayF, xyzu2: ArrayF, minimum_image: bool = False
    ) -> ArrayF: ...
    def isin(self, xyz: ArrayF) -> ArrayBool: ...

# ---------------------------------------------------------------------------
# Neighbor search
# ---------------------------------------------------------------------------

class NeighborList:
    """Result of a neighbor query — pairs within cutoff."""

    @property
    def query_point_indices(self) -> ArrayU32: ...
    @property
    def point_indices(self) -> ArrayU32: ...
    @property
    def distances(self) -> ArrayF: ...
    @property
    def dist_sq(self) -> ArrayF: ...
    @property
    def n_pairs(self) -> int: ...
    @property
    def num_points(self) -> int: ...
    @property
    def num_query_points(self) -> int: ...
    @property
    def is_self_query(self) -> bool: ...
    def pairs(self) -> ArrayI64: ...

class NeighborQuery:
    """Spatial neighbor query (freud-style)."""

    def __init__(self, box: Box, points: ArrayF, cutoff: float) -> None: ...
    def query(self, query_points: ArrayF) -> NeighborList: ...
    def query_self(self) -> NeighborList: ...

class LinkedCell:
    """Linked-cell neighbor list (legacy API; prefer NeighborQuery)."""

    def __init__(self, points: ArrayF, cutoff: float, box: Box) -> None: ...
    def pairs(self) -> ArrayI64: ...
    def update(self, points: ArrayF, box: Box) -> None: ...

# ---------------------------------------------------------------------------
# Block / Frame
# ---------------------------------------------------------------------------

class Block:
    """Heterogeneous column store (dict of typed numpy arrays)."""

    def __init__(self) -> None: ...
    def insert(self, key: str, array: npt.NDArray | Sequence[str]) -> None:
        """Store a column. Raises ``BlockDtypeError`` for object/None/ragged."""
        ...
    def view(self, key: str) -> npt.NDArray | list[str]: ...
    @property
    def nrows(self) -> Optional[int]: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def remove(self, key: str) -> None: ...
    def dtype(self, key: str) -> str: ...

class Frame:
    """Dictionary of Blocks with optional Box and metadata."""

    def __init__(self) -> None: ...
    @staticmethod
    def from_dict(data: dict[str, Any]) -> "Frame": ...
    def __getitem__(self, key: str) -> Block: ...
    def __setitem__(self, key: str, value: Block) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    @property
    def simbox(self) -> Optional[Box]: ...
    @simbox.setter
    def simbox(self, value: Optional[Box]) -> None: ...
    @property
    def meta(self) -> dict[str, str]: ...
    @meta.setter
    def meta(self, value: dict[str, str]) -> None: ...
    def validate(self) -> None: ...

# ---------------------------------------------------------------------------
# Regions (boolean compositions of primitive shapes)
# ---------------------------------------------------------------------------

class Sphere:
    """Solid sphere region."""

    def __init__(self, center: ArrayF, radius: float) -> None: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class HollowSphere:
    """Hollow sphere (spherical shell) region."""

    def __init__(
        self, center: ArrayF, inner_radius: float, outer_radius: float
    ) -> None: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class Region:
    """Composed geometric region (result of &, |, ~ operators)."""

    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

# ---------------------------------------------------------------------------
# Molecular graph
# ---------------------------------------------------------------------------

class Graph:
    """Domain-agnostic ECS *world*. Base of the hierarchy.

    Entities are stable opaque ``int`` handles (generational slotmap keys);
    removing one entity never invalidates another and a stale handle raises.
    Components live in aligned columns addressed by convention keys (see
    :data:`keys`); ``column`` exposes a zero-copy numpy view. Topology is a
    kind-tagged relation API (``register_kind`` / ``add_relation`` / …).

    Algorithms are **module-level free functions** (``translate`` / ``rotate`` /
    ``perceive_aromaticity`` / …), not methods. Chemistry vocabulary
    (``add_atom`` / ``add_bond`` / ``add_bead``) lives on the :class:`Atomistic`
    / :class:`CoarseGrain` leaves.

    Subclassable from Python — ``__new__`` accepts and ignores
    ``*args``/``**kwargs``.
    """

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    # --- entities ---
    def spawn(self) -> int: ...
    def despawn(self, h: int) -> None: ...
    def entities(self) -> List[int]: ...
    def has_entity(self, h: int) -> bool: ...
    @property
    def n_nodes(self) -> int: ...
    # --- components (convention keys; typed; missing/type-mismatch raises) ---
    def get(self, h: int, key: str) -> Union[int, float, str, None]: ...
    def set(self, h: int, key: str, value: Union[int, float, str]) -> None: ...
    def has(self, h: int, key: str) -> bool: ...
    def delete(self, h: int, key: str) -> None: ...
    def column(self, key: str) -> ArrayF: ...
    def validity(self, key: str) -> ArrayBool: ...
    # --- relations (generic, kind-tagged) ---
    def register_kind(self, kind: str, arity: int) -> None: ...
    def kinds(self) -> List[str]: ...
    def add_relation(self, kind: str, nodes: List[int]) -> int: ...
    def relation_nodes(self, kind: str, rh: int) -> List[int]: ...
    def get_relation_prop(
        self, kind: str, rh: int, key: str
    ) -> Union[int, float, str, None]: ...
    def set_relation_prop(
        self, kind: str, rh: int, key: str, value: Union[int, float, str]
    ) -> None: ...
    def remove_relation(self, kind: str, rh: int) -> None: ...
    def n_relations(self, kind: str) -> int: ...
    # --- adopt (zero-copy move) ---
    def adopt(self, other: "Graph") -> None: ...

class Atomistic(Graph):
    """All-atom leaf — holds a core ``Atomistic`` from construction.

    Registers the ``bonds``/``angles``/``dihedrals``/``impropers`` kinds and
    exposes the atom/bond/angle/dihedral/improper builders. The generic
    :class:`Graph` API operates on this leaf's own graph. Owns its
    :meth:`to_frame` / :meth:`from_frame` (domain conversions); it is never
    *converted* from a bare :class:`Graph`.
    """

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def add_atom(
        self,
        symbol: str,
        x: Optional[float] = None,
        y: Optional[float] = None,
        z: Optional[float] = None,
    ) -> int: ...
    def add_bond(self, a: int, b: int) -> int: ...
    def add_angle(self, i: int, j: int, k: int) -> int: ...
    def add_dihedral(self, i: int, j: int, k: int, l: int) -> int: ...
    def add_improper(self, i: int, j: int, k: int, l: int) -> int: ...
    @property
    def n_atoms(self) -> int: ...
    def to_frame(self) -> Frame: ...
    @staticmethod
    def from_frame(frame: Frame) -> "Atomistic": ...

class CoarseGrain(Graph):
    """Coarse-grained leaf — holds a core ``CoarseGrain`` from construction.

    ``add_bead`` writes ``bead_type``; registers the CG ``bonds`` kind. Owns its
    :meth:`to_frame` / :meth:`from_frame`.
    """

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def add_bead(
        self,
        bead_type: str,
        x: Optional[float] = None,
        y: Optional[float] = None,
        z: Optional[float] = None,
    ) -> int: ...
    def add_bond(self, a: int, b: int) -> int: ...
    @property
    def n_beads(self) -> int: ...
    def to_frame(self) -> Frame: ...
    @staticmethod
    def from_frame(frame: Frame) -> "CoarseGrain": ...

# ---------------------------------------------------------------------------
# Systems — module-level free functions over a graph world
# ---------------------------------------------------------------------------

def translate(mol: Graph, delta: List[float]) -> None: ...
def rotate(
    mol: Graph, axis: List[float], angle: float, about: Optional[List[float]] = None
) -> None: ...
def perceive_aromaticity(mol: Atomistic) -> int: ...
def add_hydrogens(mol: Atomistic) -> Atomistic: ...
def find_rings(mol: Atomistic) -> List[List[int]]: ...
def compute_gasteiger_charges(
    mol: Atomistic, n_iter: int = 6
) -> List[Tuple[int, float, float]]: ...

# ---------------------------------------------------------------------------
# Field-name convention (mirrors molrs_core::keys)
# ---------------------------------------------------------------------------

class keys:
    """String constants for the component/field naming convention."""

    X: str
    Y: str
    Z: str
    COORDS: List[str]
    ELEMENT: str
    BEAD_TYPE: str
    CHARGE: str
    ORDER: str
    MASS: str
    TYPE: str
    ID: str
    MOL_ID: str
    SYMBOL: str
    NAME: str

# ---------------------------------------------------------------------------
# SMILES
# ---------------------------------------------------------------------------

class SmilesIR:
    """Intermediate representation of a parsed SMILES string."""

    @property
    def n_components(self) -> int: ...
    def to_atomistic(self) -> Atomistic: ...

def parse_smiles(smiles: str) -> SmilesIR: ...

# ---------------------------------------------------------------------------
# I/O — readers and writers
# ---------------------------------------------------------------------------

def read_pdb(path: str) -> Frame: ...
def read_xyz(path: str) -> Frame: ...
def read_xyz_trajectory(path: str) -> list[Frame]: ...
def read_lammps(path: str) -> Frame: ...
def read_lammps_traj(path: str) -> list[Frame]: ...
def read_gro(path: str) -> list[Frame]: ...

class LAMMPSTrajReader:
    """Lazy, indexed reader for LAMMPS dump trajectory files.

    Frames are parsed on demand via byte-offset seeks; the index of
    ``ITEM: TIMESTEP`` markers is built on the first ``len()`` /
    ``__getitem__`` / ``read_frame`` call (or eagerly via ``build_index()``).

    Supports the molpy ``BaseTrajectoryReader`` surface: ``read_frame``,
    ``read_frames``, ``read_range``, ``read_all``, ``n_frames``, slicing,
    ``close()``, and use as a context manager.
    """

    def __init__(self, path: str) -> None: ...
    @property
    def n_frames(self) -> int: ...
    def build_index(self) -> None: ...
    def read_frame(self, index: int) -> Frame: ...
    def read_frames(self, indices: Sequence[int]) -> list[Frame]: ...
    def read_range(
        self, start: int = ..., stop: Optional[int] = ..., step: int = ...
    ) -> list[Frame]: ...
    def read_all(self) -> list[Frame]: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> Frame: ...
    @overload
    def __getitem__(self, key: slice) -> list[Frame]: ...
    def __iter__(self) -> "LAMMPSTrajReader": ...
    def __next__(self) -> Frame: ...
    def __enter__(self) -> "LAMMPSTrajReader": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

def read_dcd(path: str) -> list[Frame]: ...

class DCDTrajReader:
    """Lazy, indexed reader for DCD trajectory files.

    Frames are parsed on demand via byte-offset seeks computed from the DCD
    header; the header is parsed on the first ``len()`` / ``__getitem__`` /
    ``read_step`` call (or eagerly via ``build_index()``).

    Supports the molpy ``BaseTrajectoryReader`` surface: ``read_frame``,
    ``read_frames``, ``read_range``, ``read_all``, ``n_frames``, slicing,
    ``close()``, and use as a context manager.
    """

    def __init__(self, path: str) -> None: ...
    @property
    def n_frames(self) -> int: ...
    def build_index(self) -> None: ...
    def read_frame(self, index: int) -> Frame: ...
    def read_frames(self, indices: Sequence[int]) -> list[Frame]: ...
    def read_range(
        self, start: int = ..., stop: Optional[int] = ..., step: int = ...
    ) -> list[Frame]: ...
    def read_all(self) -> list[Frame]: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> Frame: ...
    @overload
    def __getitem__(self, key: slice) -> list[Frame]: ...
    def __iter__(self) -> "DCDTrajReader": ...
    def __next__(self) -> Frame: ...
    def __enter__(self) -> "DCDTrajReader": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

class XYZTrajReader:
    """Lazy, indexed reader for multi-frame XYZ trajectory files.

    The molrs-native counterpart to :func:`read_xyz_trajectory` (which eagerly
    returns ``list[Frame]``). Exposes the same molpy ``BaseTrajectoryReader``
    surface as :class:`DCDTrajReader`: ``read_frame``, ``read_frames``,
    ``read_range``, ``read_all``, ``n_frames``, slicing, ``close()``, and use
    as a context manager.
    """

    def __init__(self, path: str) -> None: ...
    @property
    def n_frames(self) -> int: ...
    def build_index(self) -> None: ...
    def read_frame(self, index: int) -> Frame: ...
    def read_frames(self, indices: Sequence[int]) -> list[Frame]: ...
    def read_range(
        self, start: int = ..., stop: Optional[int] = ..., step: int = ...
    ) -> list[Frame]: ...
    def read_all(self) -> list[Frame]: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> Frame: ...
    @overload
    def __getitem__(self, key: slice) -> list[Frame]: ...
    def __iter__(self) -> "XYZTrajReader": ...
    def __next__(self) -> Frame: ...
    def __enter__(self) -> "XYZTrajReader": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

def read_chgcar_file(path: str) -> Frame: ...
def read_cube_file(path: str) -> Frame: ...
def write_cube_file(path: str, frame: Frame) -> None: ...
def write_pdb(path: str, frame: Frame) -> None: ...
def write_xyz(path: str, frame: Frame) -> None: ...
def write_lammps(path: str, frame: Frame) -> None: ...
def write_lammps_traj(path: str, frames: Sequence[Frame]) -> None: ...
def write_dcd(path: str, frames: Sequence[Frame]) -> None: ...
def write_gro(path: str, frame: Frame) -> None: ...

# ---------------------------------------------------------------------------
# Signal processing
# ---------------------------------------------------------------------------

def signal_acf_fft(data: ArrayF, max_lag: int) -> ArrayF: ...
def signal_apply_window(data: ArrayF, window_type: str, axis: int = 0) -> ArrayF: ...
def signal_frequency_grid(n_fft: int, dt: float) -> ArrayF: ...

# ---------------------------------------------------------------------------
# 3D coordinate generation (embed)
# ---------------------------------------------------------------------------

class ConformerStageReport:
    """Per-stage report from the conformer generation pipeline."""

    @property
    def stage(self) -> str: ...
    @property
    def energy_before(self) -> Optional[float]: ...
    @property
    def energy_after(self) -> Optional[float]: ...
    @property
    def steps(self) -> int: ...
    @property
    def converged(self) -> bool: ...
    @property
    def elapsed_ms(self) -> int: ...

class ConformerReport:
    """Aggregate report from a conformer generation run."""

    @property
    def final_energy(self) -> Optional[float]: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def stages(self) -> list[ConformerStageReport]: ...

class Conformer:
    """3D conformer generator.

    Construct with the desired generation parameters, then call
    :meth:`generate` to produce coordinates. Subclassable.
    """

    def __init__(
        self,
        speed: str = "medium",
        add_hydrogens: bool = True,
        seed: Optional[int] = None,
    ) -> None: ...
    def generate(self, mol: Atomistic) -> tuple[Atomistic, ConformerReport]: ...

# ---------------------------------------------------------------------------
# Force field
# ---------------------------------------------------------------------------

class ForceField:
    @property
    def name(self) -> str: ...
    def style_names(self) -> list[str]: ...

class Potentials:
    def __len__(self) -> int: ...
    def eval(self, coords: ArrayF) -> tuple[float, ArrayF]: ...
    def energy(self, coords: ArrayF) -> float: ...

class MMFFTypifier:
    def __init__(self) -> None: ...
    def typify(self, mol: Atomistic) -> Frame: ...
    def build(self, mol: Atomistic) -> Potentials: ...
    def forcefield(self) -> ForceField: ...

def read_forcefield_xml(path: str) -> ForceField: ...
def extract_coords(frame: Frame) -> ArrayF: ...

# ---------------------------------------------------------------------------
# MolRec / Trajectory / Observables
# ---------------------------------------------------------------------------

class Trajectory:
    def __init__(
        self,
        frames: Sequence[Frame],
        step: Optional[ArrayI64] = None,
        time: Optional[ArrayF] = None,
    ) -> None: ...
    @staticmethod
    def from_frames(
        frames: Sequence[Frame],
        step: Optional[ArrayI64] = None,
        time: Optional[ArrayF] = None,
    ) -> Trajectory: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Frame: ...
    @property
    def frames(self) -> list[Frame]: ...
    @property
    def step(self) -> Optional[ArrayI64]: ...
    @property
    def time(self) -> Optional[ArrayF]: ...

_ObservableScalarData = npt.NDArray | float | int | bool | str | list[str]

class ScalarObservable:
    def __init__(
        self,
        name: str,
        data: _ObservableScalarData,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def data(self) -> npt.NDArray | list[str] | str: ...
    @property
    def kind(self) -> str: ...

class VectorObservable:
    def __init__(
        self,
        name: str,
        data: _ObservableScalarData,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def data(self) -> npt.NDArray | list[str] | str: ...
    @property
    def kind(self) -> str: ...

_AnyObservable = ScalarObservable | VectorObservable

class Observables:
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def __contains__(self, name: str) -> bool: ...
    def get(self, name: str) -> Optional[_AnyObservable]: ...
    def add(self, observable: _AnyObservable) -> None: ...
    def add_scalar(
        self,
        name: str,
        data: _ObservableScalarData,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> ScalarObservable: ...
    def add_vector(
        self,
        name: str,
        data: _ObservableScalarData,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> VectorObservable: ...

class MolRec:
    def __init__(self) -> None: ...
    def set_frame(self, frame: Frame) -> None: ...
    def add_frame(self, frame: Frame) -> None: ...
    def set_trajectory(self, trajectory: Trajectory) -> None: ...
    def set_forcefield(self, forcefield: ForceField) -> None: ...
    @staticmethod
    def read_zarr(path: str) -> MolRec: ...
    def write_zarr(self, path: str) -> None: ...
    def count_frames(self) -> int: ...
    @property
    def frame(self) -> Frame: ...
    @property
    def trajectory(self) -> Optional[Trajectory]: ...
    @property
    def observables(self) -> Observables: ...
    @property
    def meta(self) -> object: ...
    @meta.setter
    def meta(self, value: object) -> None: ...
    @property
    def method(self) -> object: ...
    @method.setter
    def method(self, value: object) -> None: ...
    @property
    def parameters(self) -> object: ...
    @parameters.setter
    def parameters(self, value: object) -> None: ...

# ---------------------------------------------------------------------------
# Analysis (compute)
#
# The Rust crate's unified `Compute` trait consumes batches of frames. Python
# wrappers accept either a single `Frame` or a `list[Frame]`; single-frame
# arguments return single results, lists return lists of results (aligned).
# ---------------------------------------------------------------------------

class RDFResult:
    """Radial distribution function g(r). Accumulated across all input frames."""

    @property
    def bin_centers(self) -> ArrayF: ...
    @property
    def rdf(self) -> ArrayF: ...
    @property
    def bin_edges(self) -> ArrayF: ...
    @property
    def n_r(self) -> ArrayF: ...
    @property
    def volume(self) -> float: ...
    @property
    def r_min(self) -> float: ...
    @property
    def n_points(self) -> int: ...
    @property
    def n_frames(self) -> int: ...

class RDF:
    def __init__(self, n_bins: int, r_max: float, r_min: float = 0.0) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: NeighborList | Sequence[NeighborList],
    ) -> RDFResult: ...

class MSDResult:
    """MSD at a single time point."""

    @property
    def mean(self) -> float: ...
    @property
    def per_particle(self) -> ArrayF: ...

class MSDTimeSeries:
    """Time series of per-frame MSD values (frame 0 is the reference)."""

    @property
    def mean(self) -> ArrayF: ...
    @property
    def per_particle(self) -> ArrayF: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> MSDResult: ...

class MSD:
    def __init__(self) -> None: ...
    def compute(self, frames: Frame | Sequence[Frame]) -> MSDTimeSeries: ...

class ClusterResult:
    @property
    def num_clusters(self) -> int: ...
    @property
    def cluster_idx(self) -> ArrayI64: ...
    @property
    def cluster_sizes(self) -> list[int]: ...

class Cluster:
    def __init__(self, min_cluster_size: int) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: NeighborList | Sequence[NeighborList],
    ) -> ClusterResult | list[ClusterResult]: ...

class ClusterCentersResult:
    """Geometric cluster centers for one frame, shape `(num_clusters, 3)`."""

    @property
    def centers(self) -> ArrayF: ...
    def __len__(self) -> int: ...

class ClusterCenters:
    """Geometric (non-mass-weighted) cluster centers."""

    def __init__(self) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
    ) -> ClusterCentersResult | list[ClusterCentersResult]: ...

class CenterOfMassResult:
    @property
    def centers_of_mass(self) -> ArrayF: ...
    @property
    def cluster_masses(self) -> ArrayF: ...

class CenterOfMass:
    """Mass-weighted cluster centers."""

    def __init__(self, masses: Optional[ArrayF] = None) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
    ) -> CenterOfMassResult | list[CenterOfMassResult]: ...

class GyrationTensor:
    """Gyration tensor per cluster; requires geometric cluster centers."""

    def __init__(self) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
        centers: ClusterCentersResult | Sequence[ClusterCentersResult],
    ) -> ArrayF | list[ArrayF]: ...

class InertiaTensor:
    """Inertia tensor per cluster; requires COM results."""

    def __init__(self, masses: Optional[ArrayF] = None) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
        com: CenterOfMassResult | Sequence[CenterOfMassResult],
    ) -> ArrayF | list[ArrayF]: ...

class RadiusOfGyration:
    """Radius of gyration per cluster; requires COM results."""

    def __init__(self, masses: Optional[ArrayF] = None) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
        com: CenterOfMassResult | Sequence[CenterOfMassResult],
    ) -> ArrayF | list[ArrayF]: ...

class DescriptorRow:
    """1-D descriptor vector used as a PCA / k-means input row."""

    def __init__(self, values: ArrayF) -> None: ...
    def __len__(self) -> int: ...

class PcaResult:
    @property
    def coords(self) -> ArrayF: ...
    @property
    def variance(self) -> tuple[float, float]: ...

class Pca2:
    """Two-component PCA."""

    def __init__(self) -> None: ...
    def compute(self, rows: Sequence[DescriptorRow]) -> PcaResult: ...

class KMeansResult:
    @property
    def labels(self) -> npt.NDArray[np.int32]: ...
    def __len__(self) -> int: ...

class KMeans:
    """k-means over a PCA projection (2-D)."""

    def __init__(self, k: int, max_iter: int = 100, seed: int = 0) -> None: ...
    def compute(self, pca: PcaResult) -> KMeansResult: ...

# ---------------------------------------------------------------------------
# freud-ported analyzers (added in 0.0.17)
# ---------------------------------------------------------------------------

class Steinhardt:
    """Bond-orientational order parameters `q_ℓ` and `w_ℓ`."""

    def __init__(
        self,
        l: Sequence[int],
        average: bool = False,
        wl: bool = False,
        wl_normalize: bool = False,
    ) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: NeighborList | Sequence[NeighborList],
    ) -> list[dict]: ...

class Nematic:
    """Nematic order parameter via Q-tensor eigenvalue."""

    def __init__(self) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        directors: Sequence[Sequence[float]],
    ) -> tuple[float, ArrayF, ArrayF, ArrayF]: ...

class Hexatic:
    """2-D hexatic order parameter `ψ_k`."""

    def __init__(self, k: int) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: NeighborList | Sequence[NeighborList],
    ) -> list[ArrayF]: ...

class SolidLiquid:
    """Frenkel-ten Wolde solid/liquid classifier."""

    def __init__(
        self, l: int, q_threshold: float = 0.7, n_threshold: int = 6
    ) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: NeighborList | Sequence[NeighborList],
    ) -> list[tuple[npt.NDArray[np.uint32], list[bool]]]: ...

class ClusterProperties:
    """Per-cluster size / center / gyration tensor aggregator."""

    def __init__(self) -> None: ...
    def with_masses(self, masses: Sequence[float]) -> ClusterProperties: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: Sequence[ClusterResult],
    ) -> list[dict]: ...

class LocalDensity:
    """Per-particle local number density in a sphere of radius r_max."""

    def __init__(self, r_max: float, diameter: float = 0.0) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: NeighborList | Sequence[NeighborList],
    ) -> list[tuple[ArrayF, ArrayF]]: ...

class GaussianDensity:
    """3-D Gaussian-smeared density grid."""

    def __init__(self, nx: int, ny: int, nz: int, sigma: float) -> None: ...
    def compute(self, frames: Frame | Sequence[Frame]) -> list[ArrayF]: ...

class BondOrder:
    """2-D (θ, φ) histogram of neighbor-bond vectors."""

    def __init__(self, n_theta: int, n_phi: int) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: NeighborList | Sequence[NeighborList],
    ) -> list[tuple[npt.NDArray[np.uint64], ArrayF, ArrayF, ArrayF]]: ...

class StaticStructureFactorDebye:
    """Closed-form Debye static structure factor S(k)."""

    def __init__(self, k_values: Sequence[float]) -> None: ...
    @staticmethod
    def linspace(k_min: float, k_max: float, n: int) -> StaticStructureFactorDebye: ...
    def compute(
        self, frames: Frame | Sequence[Frame]
    ) -> list[tuple[ArrayF, ArrayF, int]]: ...

class PMFTXY:
    """2-D (x, y) Pair Mode Fourier Transform."""

    def __init__(
        self, x_max: float, y_max: float, n_x: int, n_y: int
    ) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: NeighborList | Sequence[NeighborList],
        orientations: Sequence[Sequence[float]] | None = None,
    ) -> list[tuple[npt.NDArray[np.uint64], ArrayF, ArrayF]]: ...
