"""Type stubs for molrs Python bindings."""

from typing import Optional, Sequence
import numpy as np
import numpy.typing as npt

# Type aliases
ArrayF = npt.NDArray[np.float32]
ArrayBool = npt.NDArray[np.bool_]
ArrayU8 = npt.NDArray[np.uint8]

class Box:
    """Simulation box with periodic boundary conditions."""

    def __init__(
        self,
        h: ArrayF,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> None: ...
    @staticmethod
    def cube(
        a: float,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> Box: ...
    @staticmethod
    def ortho(
        lengths: ArrayF,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> Box: ...
    def volume(self) -> float: ...
    def lattice(self, index: int) -> ArrayF: ...
    @property
    def h(self) -> ArrayF: ...
    @property
    def origin(self) -> ArrayF: ...
    @property
    def pbc(self) -> ArrayBool: ...
    def lengths(self) -> ArrayF: ...
    def to_frac(self, xyz: ArrayF) -> ArrayF: ...
    def to_cart(self, xyzs: ArrayF) -> ArrayF: ...
    def wrap(self, xyzu: ArrayF) -> ArrayF: ...
    def delta(
        self, xyzu1: ArrayF, xyzu2: ArrayF, minimum_image: bool = False
    ) -> ArrayF: ...
    def isin(self, xyz: ArrayF) -> ArrayBool: ...

class LinkedCell:
    """Linked-cell neighbor list for pairwise distance queries."""

    def __init__(self, points: ArrayF, cutoff: float, box: Box) -> None: ...
    def pairs(self) -> npt.NDArray[np.int64]: ...
    def update(self, points: ArrayF, box: Box) -> None: ...

class Block:
    """Heterogeneous column store (dict of typed numpy arrays)."""

    def __init__(self) -> None: ...
    def insert(self, key: str, array: npt.NDArray | Sequence[str]) -> None: ...
    def view(self, key: str) -> npt.NDArray | list[str]: ...
    @property
    def nrows(self) -> Optional[int]: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def remove(self, key: str) -> None: ...
    def dtype(self, key: str) -> str: ...

class Frame:
    """Dictionary of Blocks with optional SimBox and metadata."""

    def __init__(self) -> None: ...
    def __getitem__(self, key: str) -> Block: ...
    def __setitem__(self, key: str, block: Block) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    @property
    def simbox(self) -> Optional[Box]: ...
    @simbox.setter
    def simbox(self, value: Optional[Box]) -> None: ...
    @property
    def meta(self) -> dict[str, str]: ...
    @meta.setter
    def meta(self, value: dict[str, str]) -> None: ...
    def validate(self) -> None: ...

def read_pdb(path: str) -> Frame: ...
def read_xyz(path: str) -> Frame: ...
def read_xyz_trajectory(path: str) -> list[Frame]: ...
def read_lammps(path: str) -> Frame: ...
def read_lammps_traj(path: str) -> list[Frame]: ...

class Sphere:
    """Solid sphere region."""

    def __init__(self, center: ArrayF, radius: float) -> None: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class HollowSphere:
    """Hollow sphere (spherical shell) region."""

    def __init__(
        self, center: ArrayF, inner_radius: float, outer_radius: float
    ) -> None: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class Region:
    """Composed geometric region (result of &, |, ~ operators)."""

    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class InsideBox:
    """Box constraint: atoms must be within a rectangular box."""

    def __init__(self, min: Sequence[float], max: Sequence[float]) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class InsideSphere:
    """Sphere constraint: atoms must be within a sphere."""

    def __init__(self, radius: float, center: Sequence[float]) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class OutsideSphere:
    """Outside sphere constraint."""

    def __init__(self, radius: float, center: Sequence[float]) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class AbovePlane:
    """Above plane constraint: n.x >= d."""

    def __init__(self, normal: Sequence[float], distance: float) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class BelowPlane:
    """Below plane constraint: n.x <= d."""

    def __init__(self, normal: Sequence[float], distance: float) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class MoleculeConstraint:
    """Composed constraint (result of .and_() operations)."""

    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class Target:
    """Describes one type of molecule to be packed."""

    def __init__(self, frame: Frame, count: int) -> None: ...
    @staticmethod
    def from_coords(
        positions: ArrayF, radii: ArrayF, count: int
    ) -> Target: ...
    def with_name(self, name: str) -> Target: ...
    def with_constraint(
        self,
        constraint: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> Target: ...
    def with_constraint_for_atoms(
        self,
        indices: Sequence[int],
        constraint: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> Target: ...
    def with_maxmove(self, maxmove: int) -> Target: ...
    def with_center(self) -> Target: ...
    def without_centering(self) -> Target: ...
    def constrain_rotation_x(
        self, center_deg: float, half_width_deg: float
    ) -> Target: ...
    def constrain_rotation_y(
        self, center_deg: float, half_width_deg: float
    ) -> Target: ...
    def constrain_rotation_z(
        self, center_deg: float, half_width_deg: float
    ) -> Target: ...
    def fixed_at(self, position: Sequence[float]) -> Target: ...
    def fixed_at_with_euler(
        self, position: Sequence[float], euler: Sequence[float]
    ) -> Target: ...
    @property
    def natoms(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def elements(self) -> list[str]: ...
    @property
    def is_fixed(self) -> bool: ...

class Packer:
    """Molecular packer (Packmol port)."""

    def __init__(
        self, tolerance: float = 2.0, precision: float = 0.01
    ) -> None: ...
    def with_tolerance(self, tolerance: float) -> Packer: ...
    def with_precision(self, precision: float) -> Packer: ...
    def with_maxit(self, maxit: int) -> Packer: ...
    def with_nloop0(self, nloop0: int) -> Packer: ...
    def with_sidemax(self, sidemax: float) -> Packer: ...
    def with_movefrac(self, movefrac: float) -> Packer: ...
    def with_movebadrandom(self, enabled: bool) -> Packer: ...
    def with_disable_movebad(self, disabled: bool) -> Packer: ...
    def with_pbc(self, min: Sequence[float], max: Sequence[float]) -> Packer: ...
    def with_pbc_box(self, lengths: Sequence[float]) -> Packer: ...
    def with_progress(self, enabled: bool) -> Packer: ...
    def pack(
        self,
        targets: list[Target],
        max_loops: int = 200,
        seed: Optional[int] = None,
    ) -> PackResult: ...

class PackResult:
    """Result of a packing run."""

    @property
    def positions(self) -> ArrayF: ...
    @property
    def elements(self) -> list[str]: ...
    @property
    def frame(self) -> Frame: ...
    @property
    def converged(self) -> bool: ...
    @property
    def fdist(self) -> float: ...
    @property
    def frest(self) -> float: ...
    @property
    def natoms(self) -> int: ...

class Trajectory:
    def __init__(
        self,
        frames: list[Frame],
        step: Optional[npt.NDArray[np.int64]] = None,
        time: Optional[ArrayF] = None,
        box: Optional[Box | list[Box]] = None,
    ) -> None: ...
    @staticmethod
    def from_frames(
        frames: list[Frame],
        step: Optional[npt.NDArray[np.int64]] = None,
        time: Optional[ArrayF] = None,
        box: Optional[Box | list[Box]] = None,
    ) -> Trajectory: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Frame: ...
    @property
    def frames(self) -> list[Frame]: ...
    @property
    def step(self) -> Optional[npt.NDArray[np.int64]]: ...
    @property
    def time(self) -> Optional[ArrayF]: ...
    @property
    def box_(self) -> Box | list[Box] | None: ...

class ScalarObservable:
    def __init__(
        self,
        name: str,
        data: npt.NDArray | float | int | bool | str | list[str],
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def data(self) -> npt.NDArray | list[str] | str: ...
    @property
    def kind(self) -> str: ...

class VectorObservable:
    def __init__(
        self,
        name: str,
        data: npt.NDArray | float | int | bool | str | list[str],
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def data(self) -> npt.NDArray | list[str] | str: ...
    @property
    def kind(self) -> str: ...

class FieldObservable:
    @staticmethod
    def uniform_grid(
        name: str,
        values: ArrayF,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
        origin: Optional[ArrayF] = None,
        basis_vectors: Optional[npt.NDArray[np.float32]] = None,
        spacing: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> FieldObservable: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str: ...

class Observables:
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def __contains__(self, name: str) -> bool: ...
    def get(self, name: str) -> ScalarObservable | VectorObservable | FieldObservable | None: ...
    def add(self, observable: ScalarObservable | VectorObservable | FieldObservable) -> None: ...
    def add_scalar(
        self,
        name: str,
        data: npt.NDArray | float | int | bool | str | list[str],
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> ScalarObservable: ...
    def add_vector(
        self,
        name: str,
        data: npt.NDArray | float | int | bool | str | list[str],
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> VectorObservable: ...
    def add_field(
        self,
        name: str,
        values: ArrayF,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
        origin: Optional[ArrayF] = None,
        basis_vectors: Optional[npt.NDArray[np.float32]] = None,
        spacing: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> FieldObservable: ...

class MolRec:
    def __init__(
        self,
        frame: Frame,
        trajectory: Optional[Trajectory] = None,
        meta: Optional[dict] = None,
        method: Optional[dict] = None,
        parameters: Optional[dict] = None,
        box: Optional[Box | list[Box]] = None,
    ) -> None: ...
    @staticmethod
    def from_frame(
        frame: Frame,
        meta: Optional[dict] = None,
        method: Optional[dict] = None,
        parameters: Optional[dict] = None,
        box: Optional[Box | list[Box]] = None,
    ) -> MolRec: ...
    @staticmethod
    def from_frames(
        frame: Frame,
        frames: list[Frame],
        meta: Optional[dict] = None,
        method: Optional[dict] = None,
        parameters: Optional[dict] = None,
        box: Optional[Box | list[Box]] = None,
    ) -> MolRec: ...
    @staticmethod
    def from_trajectory(
        trajectory: Trajectory,
        meta: Optional[dict] = None,
        method: Optional[dict] = None,
        parameters: Optional[dict] = None,
        box: Optional[Box | list[Box]] = None,
    ) -> MolRec: ...
    @staticmethod
    def from_forcefield(
        frame: Frame,
        forcefield: ForceField,
        meta: Optional[dict] = None,
        parameters: Optional[dict] = None,
        box: Optional[Box | list[Box]] = None,
    ) -> MolRec: ...
    @staticmethod
    def read_zarr(path: str) -> MolRec: ...
    def write_zarr(self, path: str) -> None: ...
    def count_frames(self) -> int: ...
    def frame_at(self, index: int) -> Frame: ...
    @property
    def frame(self) -> Frame: ...
    @property
    def trajectory(self) -> Optional[Trajectory]: ...
    @property
    def observables(self) -> Observables: ...
    @property
    def meta(self) -> dict: ...
    @meta.setter
    def meta(self, value: dict) -> None: ...
    @property
    def method(self) -> dict: ...
    @method.setter
    def method(self, value: dict) -> None: ...
    @property
    def parameters(self) -> dict: ...
    @parameters.setter
    def parameters(self, value: dict) -> None: ...
    @property
    def box_(self) -> Box | list[Box] | None: ...

class ForceField:
    @property
    def name(self) -> str: ...
    def style_names(self) -> list[str]: ...

def read_forcefield_xml(path: str) -> ForceField: ...

class Potentials:
    def __len__(self) -> int: ...
    def eval(self, coords: ArrayF) -> tuple[float, ArrayF]: ...
    def energy(self, coords: ArrayF) -> float: ...

class MMFFTypifier:
    def __init__(self) -> None: ...
    def typify(self, mol: "Atomistic") -> Frame: ...
    def build(self, mol: "Atomistic") -> Potentials: ...
    def forcefield(self) -> ForceField: ...

def extract_coords(frame: Frame) -> ArrayF: ...
