//! CXX bridge exposing molrs I/O and analysis to Atomiverse (C++).
//!
//! Zero-copy I/O: C++ slices → FrameView (borrowed) → write_xyz_frame.
//! Owned Frame only built when persisting to MolRec (Zarr).

use std::collections::HashMap;
use std::fs::{File, OpenOptions};
use std::io::{BufWriter, Write};

use molrs::block::block_view::BlockView;
use molrs::block::column_view::ColumnView;
use molrs::block::Block;
use molrs::frame::Frame;
use molrs::frame_view::FrameView;
use molrs::io::xyz::write_xyz_frame;
use molrs::molrec::MolRec;
use molrs::region::simbox::SimBox;
use molrs::types::F;
use ndarray::{Array1, Array2, ArrayD, ArrayView1};

mod bridge; // generated by build.rs

// ── Element lookup ───────────────────────────────────────────────────────────

fn symbol_for_z(z: i32) -> &'static str {
    match z {
        1 => "H",  2 => "He", 3 => "Li", 4 => "Be", 5 => "B",  6 => "C",
        7 => "N",  8 => "O",  9 => "F",  10 => "Ne", 11 => "Na", 12 => "Mg",
        13 => "Al", 14 => "Si", 15 => "P", 16 => "S", 17 => "Cl", 18 => "Ar",
        _ => "X",
    }
}

// ── Staging — holds borrowed references to C++ data between FFI calls ────────

struct Staging {
    symbols: Vec<String>,
    x: Vec<F>, y: Vec<F>, z: Vec<F>,
    box_mat: [F; 9],
    fields: Vec<(String, Vec<F>)>,
    scalars: Vec<(String, f64)>,
    strings: Vec<(String, String)>,
}

impl Default for Staging {
    fn default() -> Self {
        Self {
            symbols: Vec::new(),
            x: Vec::new(), y: Vec::new(), z: Vec::new(),
            box_mat: [0.0 as F; 9],
            fields: Vec::new(), scalars: Vec::new(), strings: Vec::new(),
        }
    }
}

impl Staging {
    /// Write staging data via FrameView (zero-copy).
    fn write_view<W: Write>(&self, w: &mut W) {
        let mut atoms = BlockView::new();
        atoms.insert("element", ColumnView::String(
            ArrayView1::from(&self.symbols[..]).into_dyn()));
        atoms.insert("x", ColumnView::Float(
            ArrayView1::from(&self.x[..]).into_dyn()));
        atoms.insert("y", ColumnView::Float(
            ArrayView1::from(&self.y[..]).into_dyn()));
        atoms.insert("z", ColumnView::Float(
            ArrayView1::from(&self.z[..]).into_dyn()));
        for (name, vals) in &self.fields {
            atoms.insert(name.as_str(), ColumnView::Float(
                ArrayView1::from(&vals[..]).into_dyn()));
        }

        let h = Array2::from_shape_vec((3, 3), self.box_mat.to_vec()).unwrap();
        let simbox = SimBox::new(h, Array1::zeros(3), [true, true, true]).ok();
        let meta = {
            let mut m = HashMap::new();
            for (k, v) in &self.scalars { m.insert(k.clone(), format!("{}", v)); }
            for (k, v) in &self.strings { m.insert(k.clone(), v.clone()); }
            m
        };

        let mut map = HashMap::new();
        map.insert("atoms", atoms);
        let view = FrameView::from_parts(map, simbox.as_ref(), &meta);
        write_xyz_frame(w, &view).unwrap();
    }

    /// Consume staging into an owned Frame for MolRec storage (one copy).
    fn take_frame(&mut self) -> Frame {
        let mut atoms = Block::new();
        atoms.insert("element", Array1::from_vec(std::mem::take(&mut self.symbols)).into_dyn() as ArrayD<String>).unwrap();
        atoms.insert("x", Array1::from_vec(std::mem::take(&mut self.x)).into_dyn()).unwrap();
        atoms.insert("y", Array1::from_vec(std::mem::take(&mut self.y)).into_dyn()).unwrap();
        atoms.insert("z", Array1::from_vec(std::mem::take(&mut self.z)).into_dyn()).unwrap();
        for (name, vals) in self.fields.drain(..) {
            atoms.insert(name.as_str(), Array1::from_vec(vals).into_dyn()).unwrap();
        }
        let mut frame = Frame::new();
        frame.insert("atoms", atoms);
        let h = Array2::from_shape_vec((3, 3), self.box_mat.to_vec()).unwrap();
        if let Ok(sb) = SimBox::new(h, Array1::zeros(3), [true, true, true]) {
            frame.simbox = Some(sb);
        }
        for (k, v) in self.scalars.drain(..) { frame.meta.insert(k, format!("{}", v)); }
        for (k, v) in self.strings.drain(..) { frame.meta.insert(k, v); }
        self.box_mat = [0.0 as F; 9];
        frame
    }
}

// ── AtvMolRec ────────────────────────────────────────────────────────────────

pub struct AtvMolRec {
    rec: MolRec,
    staging: Staging,
    n_frames: i32,
}

impl AtvMolRec {
    fn new() -> Self {
        Self {
            rec: MolRec::new(Frame::new()),
            staging: Staging::default(),
            n_frames: 0,
        }
    }
}

// ── MolRec bridge ────────────────────────────────────────────────────────────

fn molrec_new() -> Box<AtvMolRec> { Box::new(AtvMolRec::new()) }

fn molrec_set_geometry(rec: &mut AtvMolRec, type_id: &[i32],
    x: &[F], y: &[F], z: &[F], box_mat: &[F])
{
    let n = type_id.len();
    let s = &mut rec.staging;
    s.symbols = type_id.iter().map(|&z| symbol_for_z(z).to_string()).collect();
    s.x = x[..n].to_vec(); s.y = y[..n].to_vec(); s.z = z[..n].to_vec();
    if box_mat.len() >= 9 { s.box_mat.copy_from_slice(&box_mat[..9]); }
}

fn molrec_add_field(rec: &mut AtvMolRec, name: &str, values: &[F]) {
    rec.staging.fields.push((name.to_string(), values.to_vec()));
}
fn molrec_add_scalar(rec: &mut AtvMolRec, name: &str, value: f64) {
    rec.staging.scalars.push((name.to_string(), value));
}
fn molrec_add_string(rec: &mut AtvMolRec, name: &str, value: &str) {
    rec.staging.strings.push((name.to_string(), value.to_string()));
}

fn molrec_commit_frame(rec: &mut AtvMolRec) {
    let frame = rec.staging.take_frame(); // one copy for persistence
    rec.rec.add_frame(frame);
    rec.n_frames += 1;
}

fn molrec_clear(rec: &mut AtvMolRec) {
    rec.rec = MolRec::new(Frame::new());
    rec.staging = Staging::default();
    rec.n_frames = 0;
}

fn molrec_n_frames(rec: &AtvMolRec) -> i32 { rec.n_frames }

// ── I/O ──────────────────────────────────────────────────────────────────────

fn xyz_write(path: &str, rec: &AtvMolRec) {
    let f = File::create(path).expect("xyz_write: create");
    let mut w = BufWriter::new(f);
    for i in 0..rec.rec.count_frames() {
        if let Some(frame) = rec.rec.frame_at(i) {
            write_xyz_frame(&mut w, &frame).unwrap();
        }
    }
}
fn xyz_write_ext(path: &str, rec: &AtvMolRec) { xyz_write(path, rec); }

fn xyz_append(path: &str, rec: &AtvMolRec) {
    if rec.staging.symbols.is_empty() && rec.n_frames == 0 { return; }
    let f = OpenOptions::new().create(true).append(true).open(path)
        .expect("xyz_append: open");
    let mut w = BufWriter::new(f);

    if !rec.staging.symbols.is_empty() {
        rec.staging.write_view(&mut w); // zero-copy via FrameView
    } else if let Some(frame) = rec.rec.frame_at(rec.rec.count_frames() - 1) {
        write_xyz_frame(&mut w, &frame).unwrap();
    }
}
fn xyz_append_ext(path: &str, rec: &AtvMolRec) { xyz_append(path, rec); }

fn trajectory_append(path: &str, type_id: &[i32], x: &[F], y: &[F], z: &[F], step: i32) {
    let n = type_id.len();
    let f = OpenOptions::new().create(true).append(true).open(path).expect("traj: open");
    let mut w = BufWriter::new(f);
    writeln!(w, "{}", n).unwrap();
    writeln!(w, "Step {}", step).unwrap();
    for i in 0..n { writeln!(w, "{}  {:.6}  {:.6}  {:.6}", type_id[i], x[i], y[i], z[i]).unwrap(); }
}

fn molrec_write_zarr(path: &str, rec: &AtvMolRec) {
    rec.rec.write_zarr(path).expect("molrec_write_zarr: write");
}

fn molrec_print_summary(rec: &AtvMolRec) {
    let mr = &rec.rec;
    let n = mr.count_frames();
    if n == 0 { return; }
    let frame = match mr.frame_at(n - 1) { Some(f) => f, None => return };
    let meta = &frame.meta;
    let method = meta.get("method").map(|s| s.as_str()).unwrap_or("?");
    let energy: f64 = meta.get("energy").and_then(|s| s.parse().ok()).unwrap_or(0.0);
    let iters: i32 = meta.get("iterations").and_then(|s| s.parse().ok()).unwrap_or(0);
    let na: i32 = meta.get("n_alpha").and_then(|s| s.parse().ok()).unwrap_or(0);
    let nb: i32 = meta.get("n_beta").and_then(|s| s.parse().ok()).unwrap_or(0);
    let sc: f64 = meta.get("spin_contamination").and_then(|s| s.parse().ok()).unwrap_or(0.0);
    println!();
    println!("\u{2500}\u{2500}\u{2500} {} Molecular Record \u{2500}{}", method, "\u{2500}".repeat(39));
    println!("  Energy:         {:+.10} Hartree", energy);
    println!("  Iterations:     {}", iters);
    if method == "UHF" {
        println!("  Electrons:      {} alpha, {} beta  (2S+1 = {})", na, nb, na - nb + 1);
        println!("  Spin contam.:   {:.6}  (<S^2> - S*(S+1))", sc);
    } else {
        println!("  Electrons:      {}  (closed-shell)", na + nb);
    }
    // Use FrameAccess for column access
    use molrs::frame_access::FrameAccess;
    if let Some(charges) = frame.get_float("atoms", "charge") {
        let spins = frame.get_float("atoms", "spin_density");
        let elems = frame.get_string("atoms", "element");
        println!("\n  Mulliken population analysis:");
        println!("  {:<4}  {:<4}  {:>10}  {:>10}", "Atom", "Sym", "Charge", "SpinDens");
        println!("  {:<4}  {:<4}  {:>10}  {:>10}", "----", "---", "----------", "----------");
        let mut tot = 0.0 as F;
        for a in 0..charges.len() {
            let sym = elems.as_ref().and_then(|e| e.as_slice())
                .and_then(|s| s.get(a)).map(|s| s.as_str()).unwrap_or("X");
            let q = charges[a]; let sp = spins.as_ref().map(|sv| sv[a]).unwrap_or(0.0 as F);
            println!("  {:<4}  {:<4}  {:+10.6}  {:+10.6}", a, sym, q, sp);
            tot += q;
        }
        println!("  {:<4}  {:<4}  {:+10.6}", "Tot", "", tot);
    }
    println!("{}\n", "\u{2500}".repeat(57));
}

// ── RDF ──────────────────────────────────────────────────────────────────────

use molrs::compute::rdf::RDF as RdfCompute;

pub struct Rdf {
    inner: RdfCompute,
    histogram: Vec<i64>,
}

fn rdf_new(n_bins: i32, r_max: f64) -> Box<Rdf> {
    let n = n_bins as usize;
    Box::new(Rdf {
        inner: RdfCompute::new(n, r_max as F),
        histogram: vec![0i64; n],
    })
}

fn rdf_accumulate(rdf: &mut Rdf, distances: &[F], n_pairs: i32) {
    let bw = rdf.inner.bin_width();
    let nb = rdf.histogram.len();
    for i in 0..n_pairs as usize {
        let bin = (distances[i] / bw) as usize;
        if bin < nb { rdf.histogram[bin] += 1; }
    }
}

fn rdf_write(rdf: &Rdf, path: &str, n_samples: i32, n_atoms: i32, box_vol: f64) {
    let f = File::create(path).expect("rdf_write: create");
    let mut w = BufWriter::new(f);
    writeln!(w, "# r [Angstrom]   g(r)").unwrap();
    let n = n_atoms as f64;
    let rho = n / box_vol;
    let pi = std::f64::consts::PI;
    let bw = rdf.inner.bin_width() as f64;
    for i in 0..rdf.histogram.len() {
        let r = (i as f64 + 0.5) * bw;
        let r_lo = i as f64 * bw;
        let r_hi = (i as f64 + 1.0) * bw;
        let shell = (4.0 / 3.0) * pi * (r_hi.powi(3) - r_lo.powi(3));
        let ideal = n_samples as f64 * n * rho * shell;
        let gr = if ideal > 0.0 { 2.0 * rdf.histogram[i] as f64 / ideal } else { 0.0 };
        writeln!(w, "{:.6}  {:.6}", r, gr).unwrap();
    }
}
