//! Validation of the `molrs_embed::distgeom` RDKit port against RDKit
//! 2026.03.2 reference data.
//!
//! Fixtures are generated by
//! `/Users/roykid/.claude/jobs/938e961b/tmp/gen_bounds_fixtures.py`: for each
//! SMILES an SDF (AddHs, RDKit atom order) plus a JSON carrying RDKit's
//! already-smoothed `rdDistGeom.GetMoleculeBoundsMatrix` matrix.
//!
//! We load the SDF into a `MolGraph` (preserving atom order + Kekulé bond
//! orders), build + triangle-smooth our bounds, and assert per-element
//! agreement < 1e-3 Å with the RDKit matrix.

use std::path::{Path, PathBuf};

use molrs::molgraph::{Atom, MolGraph, PropValue};
use molrs_embed::distgeom::{
    self, BoundsMatrix, ChiralSign, EtkdgVersion, build_bounds, smooth_bounds,
};

const TOL: f64 = 1.0e-3;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/embed/fixtures")
}

/// Minimal V2000 SDF loader preserving atom order and bond orders.
fn load_sdf(path: &Path) -> MolGraph {
    let text = std::fs::read_to_string(path).expect("read sdf");
    let lines: Vec<&str> = text.lines().collect();
    let counts = lines[3];
    let n_atoms: usize = counts[0..3].trim().parse().expect("n_atoms");
    let n_bonds: usize = counts[3..6].trim().parse().expect("n_bonds");

    let mut g = MolGraph::new();
    let mut ids = Vec::with_capacity(n_atoms);
    for k in 0..n_atoms {
        let line = lines[4 + k];
        let x: f64 = line[0..10].trim().parse().expect("x");
        let y: f64 = line[10..20].trim().parse().expect("y");
        let z: f64 = line[20..30].trim().parse().expect("z");
        let element = line[31..34].trim().to_string();
        ids.push(g.add_atom(Atom::xyz(&element, x, y, z)));
    }
    for k in 0..n_bonds {
        let line = lines[4 + n_atoms + k];
        let i: usize = line[0..3].trim().parse::<usize>().expect("bond i") - 1;
        let j: usize = line[3..6].trim().parse::<usize>().expect("bond j") - 1;
        let order: f64 = line[6..9].trim().parse().expect("bond order");
        let bid = g.add_bond(ids[i], ids[j]).expect("add bond");
        g.get_bond_mut(bid)
            .expect("bond")
            .props
            .insert("order".to_string(), PropValue::F64(order));
    }
    g
}

/// Parse the `"bounds"` nested float array out of the fixture JSON without a
/// serde dependency. The JSON is machine-generated and well-formed, so a
/// targeted scan suffices.
fn load_bounds_json(path: &Path) -> Vec<Vec<f64>> {
    let text = std::fs::read_to_string(path).expect("read json");
    let start = text.find("\"bounds\":").expect("bounds key") + "\"bounds\":".len();
    let bytes = text.as_bytes();
    // find the first '[' (outer array) after the key
    let mut i = start;
    while bytes[i] != b'[' {
        i += 1;
    }
    let outer_open = i;
    // find the matching ']' for the outer array
    let mut depth = 0i32;
    let mut outer_close = outer_open;
    for (k, &b) in bytes.iter().enumerate().skip(outer_open) {
        if b == b'[' {
            depth += 1;
        } else if b == b']' {
            depth -= 1;
            if depth == 0 {
                outer_close = k;
                break;
            }
        }
    }
    let inner = &text[outer_open + 1..outer_close];
    // split into rows on top-level '[' .. ']'
    let mut rows = Vec::new();
    let ib = inner.as_bytes();
    let mut p = 0;
    while p < ib.len() {
        if ib[p] == b'[' {
            let mut q = p + 1;
            while ib[q] != b']' {
                q += 1;
            }
            let row: Vec<f64> = inner[p + 1..q]
                .split(',')
                .filter(|s| !s.trim().is_empty())
                .map(|s| s.trim().parse::<f64>().expect("float"))
                .collect();
            rows.push(row);
            p = q + 1;
        } else {
            p += 1;
        }
    }
    rows
}

/// Max absolute deviation between our matrix and the RDKit reference.
fn max_abs_dev(ours: &BoundsMatrix, reference: &[Vec<f64>]) -> (f64, usize, usize) {
    let n = ours.len();
    let dense = ours.to_dense();
    let mut worst = 0.0_f64;
    let mut wi = 0;
    let mut wj = 0;
    for i in 0..n {
        for j in 0..n {
            let d = (dense[i][j] - reference[i][j]).abs();
            if d > worst {
                worst = d;
                wi = i;
                wj = j;
            }
        }
    }
    (worst, wi, wj)
}

fn check_molecule(name: &str) -> f64 {
    let dir = fixtures_dir();
    let mol = load_sdf(&dir.join(format!("{name}.sdf")));
    let reference = load_bounds_json(&dir.join(format!("{name}.json")));

    let mut bounds = build_bounds(&mol).expect("build bounds");
    smooth_bounds(&mut bounds).expect("smooth");

    assert_eq!(bounds.len(), reference.len(), "{name}: atom count mismatch");
    let (worst, wi, wj) = max_abs_dev(&bounds, &reference);
    println!("{name}: max abs deviation = {worst:.6} Å at ({wi},{wj})");
    worst
}

#[test]
fn bounds_match_rdkit_butane() {
    assert!(check_molecule("butane") < TOL);
}

#[test]
fn bounds_match_rdkit_cyclohexane() {
    assert!(check_molecule("cyclohexane") < TOL);
}

#[test]
fn bounds_match_rdkit_benzene() {
    assert!(check_molecule("benzene") < TOL);
}

#[test]
fn bounds_match_rdkit_biphenyl() {
    assert!(check_molecule("biphenyl") < TOL);
}

#[test]
fn bounds_match_rdkit_glycine() {
    assert!(check_molecule("glycine") < TOL);
}

#[test]
fn triangle_inequalities_hold_after_smoothing() {
    for name in ["butane", "cyclohexane", "benzene", "biphenyl", "glycine"] {
        let mol = load_sdf(&fixtures_dir().join(format!("{name}.sdf")));
        let mut bounds = build_bounds(&mol).expect("bounds");
        smooth_bounds(&mut bounds).expect("smooth");
        let n = bounds.len();
        // no lower > upper
        for i in 0..n {
            for j in (i + 1)..n {
                assert!(
                    bounds.lower(i, j) <= bounds.upper(i, j) + 1e-9,
                    "{name}: lower>upper at ({i},{j})"
                );
            }
        }
        // triangle inequalities upper[i][j] <= upper[i][k] + upper[k][j]
        for i in 0..n {
            for j in (i + 1)..n {
                for k in 0..n {
                    if k == i || k == j {
                        continue;
                    }
                    assert!(
                        bounds.upper(i, j) <= bounds.upper(i, k) + bounds.upper(k, j) + 1e-6,
                        "{name}: triangle upper violated ({i},{j},{k})"
                    );
                    assert!(
                        bounds.lower(i, j)
                            >= (bounds.lower(i, k) - bounds.upper(k, j)).abs() - 1e-6
                            || bounds.lower(i, j) >= 0.0,
                        "{name}: triangle lower violated ({i},{j},{k})"
                    );
                }
            }
        }
    }
}

#[test]
fn inconsistent_bounds_make_smoothing_fail() {
    let mol = load_sdf(&fixtures_dir().join("butane.sdf"));
    let mut bounds = build_bounds(&mol).expect("bounds");
    // Inject an impossible bound: force a far pair's lower above any plausible
    // upper so triangle smoothing cannot reconcile it.
    bounds.set_lower(0, 3, 50.0);
    bounds.set_upper(0, 3, 60.0);
    // also tighten an intermediate upper so the lower can't be satisfied
    bounds.set_upper(0, 1, 0.1);
    bounds.set_upper(1, 2, 0.1);
    bounds.set_upper(2, 3, 0.1);
    let res = smooth_bounds(&mut bounds);
    assert!(res.is_err(), "expected inconsistent bounds to error");
}

#[test]
fn chiral_sign_flips_between_r_and_s() {
    // (R)- and (S)-bromochlorofluoromethane: same graph, mirror-image 3D.
    // Build both directly with opposite chirality and assert the chiral
    // constraint volume sign flips.
    fn cfclbr(positive: bool) -> MolGraph {
        let mut g = MolGraph::new();
        let c = g.add_atom(Atom::xyz("C", 0.0, 0.0, 0.0));
        let f = g.add_atom(Atom::xyz("F", 1.0, 0.0, 0.0));
        let cl = g.add_atom(Atom::xyz("Cl", -0.5, 0.9, 0.0));
        let br = g.add_atom(Atom::xyz("Br", -0.5, -0.9, 0.0));
        // 4th substituent H out of plane: +z gives one handedness, -z the other.
        let zsign = if positive { 1.0 } else { -1.0 };
        let h = g.add_atom(Atom::xyz("H", 0.0, 0.0, zsign));
        for nbr in [f, cl, br, h] {
            g.add_bond(c, nbr).expect("bond");
        }
        g
    }

    let r = distgeom::build_constraints(&cfclbr(true), EtkdgVersion::Etkdgv3).expect("R");
    let s = distgeom::build_constraints(&cfclbr(false), EtkdgVersion::Etkdgv3).expect("S");

    let r_sign = r.chiral.first().expect("R chiral").sign;
    let s_sign = s.chiral.first().expect("S chiral").sign;
    println!("R sign = {r_sign:?}, S sign = {s_sign:?}");
    assert_ne!(r_sign, ChiralSign::Unknown);
    assert_ne!(s_sign, ChiralSign::Unknown);
    assert_ne!(r_sign, s_sign, "R and S must have opposite chiral signs");
}
