//! SMARTS engine validation against RDKit `GetSubstructMatches(uniquify=False)`.
//!
//! Fixtures are generated by `gen_smarts_fixtures.py` (RDKit 2026.03.2):
//!   * one V2000 SDF per molecule (RDKit atom order preserved, Kekulé bonds);
//!   * `matches.json` carrying, per molecule, the per-atom / per-bond aromatic
//!     flags RDKit perceived, plus the reference match tuples per pattern.
//!
//! Aromaticity is the key correctness lever: `Atomistic` has no aromatic model,
//! so we *transplant* RDKit's perception into the graph — aromatic bonds get
//! order `1.5` and every atom carries an explicit `is_aromatic` prop. The
//! engine then sees exactly the aromaticity RDKit used, so `a` / `c` / `:`
//! queries agree by construction.

use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;

use molrs::{Atom, AtomId, Atomistic, PropValue, SmartsPattern};
use serde_json::Value;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("core")
        .join("fixtures")
        .join("smarts")
}

/// Minimal V2000 molfile loader: reads element + connectivity + bond order.
/// Coordinates are parsed but unused by SMARTS.
fn load_sdf(path: &PathBuf) -> (Atomistic, Vec<AtomId>) {
    let text = fs::read_to_string(path).expect("read sdf");
    let lines: Vec<&str> = text.lines().collect();
    // Line 3 (index 3) is the counts line: "aaabbb...".
    let counts = lines[3];
    let n_atoms: usize = counts[0..3].trim().parse().expect("atom count");
    let n_bonds: usize = counts[3..6].trim().parse().expect("bond count");

    let mut g = Atomistic::new();
    let mut ids = Vec::with_capacity(n_atoms);
    for i in 0..n_atoms {
        let l = lines[4 + i];
        // Columns: x(0..10) y(10..20) z(20..30) symbol(31..34)
        let x: f64 = l[0..10].trim().parse().unwrap_or(0.0);
        let y: f64 = l[10..20].trim().parse().unwrap_or(0.0);
        let z: f64 = l[20..30].trim().parse().unwrap_or(0.0);
        let sym = l[31..].split_whitespace().next().unwrap_or("C");
        ids.push(g.add_atom(Atom::xyz(sym, x, y, z)));
    }
    for b in 0..n_bonds {
        let l = lines[4 + n_atoms + b];
        let ai: usize = l[0..3].trim().parse::<usize>().unwrap() - 1;
        let aj: usize = l[3..6].trim().parse::<usize>().unwrap() - 1;
        let order: f64 = l[6..9].trim().parse().unwrap_or(1.0);
        let bid = g.add_bond(ids[ai], ids[aj]).expect("add bond");
        g.set_bond_prop(bid, "order", PropValue::F64(order))
            .unwrap();
    }
    (g, ids)
}

/// Transplant RDKit's aromaticity + formal charge into the graph.
fn apply_flags(g: &mut Atomistic, ids: &[AtomId], meta: &Value) {
    let atom_arom = meta["atom_aromatic"].as_array().unwrap();
    let charges = meta["formal_charge"].as_array().unwrap();
    for (k, &id) in ids.iter().enumerate() {
        let arom = atom_arom[k].as_i64().unwrap();
        let chg = charges[k].as_i64().unwrap();
        g.set_atom(id, "is_aromatic", PropValue::Int(arom as i32))
            .unwrap();
        g.set_atom(id, "formal_charge", PropValue::Int(chg as i32))
            .unwrap();
    }
    // Mark aromatic bonds (order 1.5 + is_aromatic prop).
    let bond_arom = meta["bond_aromatic"].as_array().unwrap();
    for entry in bond_arom {
        if entry["aromatic"].as_i64().unwrap() == 0 {
            continue;
        }
        let i = entry["i"].as_u64().unwrap() as usize;
        let j = entry["j"].as_u64().unwrap() as usize;
        let (ai, aj) = (ids[i], ids[j]);
        // Locate the matching bond and re-flag it.
        let bid = g
            .bonds()
            .find(|(_, b)| {
                (b.nodes[0] == ai && b.nodes[1] == aj) || (b.nodes[0] == aj && b.nodes[1] == ai)
            })
            .map(|(bid, _)| bid)
            .expect("aromatic bond present");
        g.set_bond_prop(bid, "order", PropValue::F64(1.5)).unwrap();
        g.set_bond_prop(bid, "is_aromatic", PropValue::Int(1))
            .unwrap();
    }
}

/// Convert a molrs match (query-atom-ordered AtomIds) to RDKit atom-index
/// tuple using the SDF row order (= RDKit atom order).
fn match_to_indices(
    m: &[AtomId],
    id_to_row: &std::collections::HashMap<AtomId, usize>,
) -> Vec<usize> {
    m.iter().map(|id| id_to_row[id]).collect()
}

fn load_fixtures() -> Value {
    let path = fixtures_dir().join("matches.json");
    serde_json::from_str(&fs::read_to_string(path).expect("read matches.json")).unwrap()
}

/// Build one molecule graph + RDKit-order row map.
fn build_mol(
    name: &str,
    fixtures: &Value,
) -> (Atomistic, std::collections::HashMap<AtomId, usize>) {
    let (mut g, ids) = load_sdf(&fixtures_dir().join(format!("{name}.sdf")));
    apply_flags(&mut g, &ids, &fixtures["molecules"][name]);
    let id_to_row = ids.iter().enumerate().map(|(row, &id)| (id, row)).collect();
    (g, id_to_row)
}

/// The main scientific gate: every (pattern, molecule) pair must match RDKit.
#[test]
fn test_matches_equal_rdkit() {
    let fixtures = load_fixtures();
    let patterns: Vec<String> = fixtures["patterns"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let mol_names: Vec<String> = fixtures["molecules"]
        .as_object()
        .unwrap()
        .keys()
        .cloned()
        .collect();

    let mut pass = 0usize;
    let mut total = 0usize;
    let mut failures: Vec<String> = Vec::new();

    for name in &mol_names {
        let (g, id_to_row) = build_mol(name, &fixtures);
        for p in &patterns {
            total += 1;
            let pat = SmartsPattern::parse(p).unwrap_or_else(|e| panic!("parse {p:?}: {e}"));
            let got: BTreeSet<Vec<usize>> = pat
                .find_matches(&g)
                .iter()
                .map(|m| match_to_indices(m, &id_to_row))
                .collect();
            let want: BTreeSet<Vec<usize>> = fixtures["matches"][name][p]
                .as_array()
                .unwrap()
                .iter()
                .map(|t| {
                    t.as_array()
                        .unwrap()
                        .iter()
                        .map(|x| x.as_u64().unwrap() as usize)
                        .collect()
                })
                .collect();
            if got == want {
                pass += 1;
            } else {
                failures.push(format!(
                    "  {name} :: {p}\n     got  {got:?}\n     want {want:?}"
                ));
            }
        }
    }

    eprintln!("SMARTS pattern x molecule pass matrix: {pass}/{total}");
    assert!(
        failures.is_empty(),
        "{} of {} pairs disagree with RDKit:\n{}",
        failures.len(),
        total,
        failures.join("\n")
    );
}

// ── ac-002: recursive SMARTS ────────────────────────────────────────────────

#[test]
fn test_recursive_carbonyl() {
    let fixtures = load_fixtures();
    let pat = SmartsPattern::parse("[$([CX3]=[OX1]):1]~[*:2]").unwrap();

    // acetamide + methyl acetate have a carbonyl; butane does not.
    for name in ["acetamide", "methyl_acetate"] {
        let (g, _) = build_mol(name, &fixtures);
        assert!(pat.has_match(&g), "{name} should match carbonyl pattern");
    }
    let (butane, _) = build_mol("butane", &fixtures);
    assert!(!pat.has_match(&butane), "butane has no carbonyl");
}

// ── ac-003: atom-map labels preserved + addressable ─────────────────────────

#[test]
fn test_atom_map_labels_torsion() {
    let pat = SmartsPattern::parse("[O:1]=[C:2]!@;-[O:3]~[C:4]").unwrap();
    assert_eq!(pat.map_label(0), Some(1));
    assert_eq!(pat.map_label(1), Some(2));
    assert_eq!(pat.map_label(2), Some(3));
    assert_eq!(pat.map_label(3), Some(4));

    let fixtures = load_fixtures();
    let (g, _) = build_mol("methyl_acetate", &fixtures);
    let matches = pat.find_matches(&g);
    assert!(
        !matches.is_empty(),
        "methyl acetate should match O=C-O-C torsion"
    );
    for m in &matches {
        // Four mutually distinct atoms.
        let set: BTreeSet<_> = m.iter().collect();
        assert_eq!(set.len(), 4, "torsion atoms must be distinct");
    }
}

// ── ac-004: invalid SMARTS returns Err without panic ────────────────────────

#[test]
fn test_invalid_smarts_returns_err() {
    for bad in ["[C", "CC=", "[Zq]", "", "((C)", "C(", "[#]", "[+", "C%1"] {
        let r = SmartsPattern::parse(bad);
        assert!(r.is_err(), "expected Err for {bad:?}, got Ok");
    }
}

// ── context-label predicate (%LABEL) ────────────────────────────────────────
//
// A general, domain-neutral SMARTS extension: a `%LABEL` token inside a bracket
// atom expression matches an atom iff an external "current label map"
// (`HashMap<AtomId, String>`) assigns that atom the exact label `LABEL`. OPLS
// layered typing supplies the per-atom assigned-type map as the label context;
// the engine itself knows nothing about OPLS. The legacy `find_matches` entry
// uses an empty label map and is unaffected.

/// Build a minimal ethanol skeleton C-C-O with explicit Hs and return the
/// graph plus the (C_methyl, C_hydroxyl, O, H_on_O) atom ids.
fn ethanol() -> (Atomistic, AtomId, AtomId, AtomId, AtomId) {
    let mut g = Atomistic::new();
    let cm = g.add_atom(Atom::xyz("C", 0.0, 0.0, 0.0));
    let ch = g.add_atom(Atom::xyz("C", 1.5, 0.0, 0.0));
    let o = g.add_atom(Atom::xyz("O", 2.5, 0.0, 0.0));
    let ho = g.add_atom(Atom::xyz("H", 3.3, 0.0, 0.0));
    g.add_bond(cm, ch).unwrap();
    g.add_bond(ch, o).unwrap();
    g.add_bond(o, ho).unwrap();
    // Hydrogens on the carbons so X4/H counts are realistic.
    for c in [cm, ch] {
        let n = if c == cm { 3 } else { 2 };
        for k in 0..n {
            let h = g.add_atom(Atom::xyz("H", 0.3 * (k as f64 + 1.0), 0.9, 0.0));
            g.add_bond(c, h).unwrap();
        }
    }
    (g, cm, ch, o, ho)
}

#[test]
fn test_bracket_h_leading_is_element() {
    // RDKit / molpy semantics: a *leading* bare `[H]` is the hydrogen element
    // (matches an H atom), while `H<n>` after another primitive is the total-H
    // count. Benzene H types depend on `[H][C;...]` meaning "an H atom bonded
    // to a carbon", so this disambiguation is load-bearing.
    let (g, _cm, _ch, _o, ho) = ethanol();

    // `[H]` alone matches every hydrogen atom (the hydroxyl H included).
    let h_elem = SmartsPattern::parse("[H]").unwrap();
    let h_matches = h_elem.find_matches(&g);
    assert!(
        h_matches.iter().any(|m| m[0] == ho),
        "[H] (leading) matches the hydroxyl H atom"
    );
    // ethanol has 1 (OH) + 3 (CH3) + 2 (CH2) = 6 hydrogens.
    assert_eq!(h_matches.len(), 6, "[H] matches all six H atoms");

    // `[CH3]` is carbon-with-3-H (a count), NOT an H atom: matches the methyl C.
    let ch3 = SmartsPattern::parse("[CH3]").unwrap();
    let ch3_matches = ch3.find_matches(&g);
    assert_eq!(ch3_matches.len(), 1, "[CH3] matches the one methyl carbon");

    // `[C;H1]` (H after another primitive) is the H-count form: the CH2 carbon
    // has 2 H, so it does NOT match H1; nothing in ethanol is a C with exactly
    // one H, so zero matches.
    let ch1 = SmartsPattern::parse("[C;H1]").unwrap();
    assert!(
        ch1.find_matches(&g).is_empty(),
        "[C;H1] is a count form (no ethanol C has exactly 1 H)"
    );

    // `[!H]` is "not the hydrogen element": matches every non-H atom.
    let not_h = SmartsPattern::parse("[!H]").unwrap();
    let non_h = not_h.find_matches(&g).len();
    assert_eq!(
        non_h,
        g.n_atoms() - 6,
        "[!H] matches the non-hydrogen atoms"
    );
}

#[test]
fn test_context_label_parses() {
    // ac-001: a def carrying `%LABEL` parses without error; one without `%`
    // parses unchanged. (Parse-only — matching is exercised below.)
    assert!(
        SmartsPattern::parse("H[O;%opls_154]").is_ok(),
        "a %LABEL def must parse"
    );
    assert!(
        SmartsPattern::parse("[C;X4]([C;%opls_145])(H)(H)H").is_ok(),
        "a %LABEL inside a branch must parse"
    );
    // Plain SMARTS still parses (no regression).
    assert!(SmartsPattern::parse("[C;X4]").is_ok());
}

#[test]
fn test_context_label_matches_only_when_assigned() {
    // ac-002: `H[O;%opls_154]` matches the hydroxyl H iff its oxygen carries the
    // assigned label `opls_154` in the supplied context map. (Unbracketed `H`
    // is the element hydrogen, mirroring the real oplsaa.xml opls_155 def;
    // bracketed `[H]` would instead be the total-H-count primitive.)
    use std::collections::HashMap;
    let (g, _cm, _ch, o, ho) = ethanol();
    let pat = SmartsPattern::parse("H[O;%opls_154]").unwrap();

    // Empty context: nothing has the label, so no match.
    let empty: HashMap<AtomId, String> = HashMap::new();
    assert!(
        pat.find_matches_with_labels(&g, &empty).is_empty(),
        "no label assigned -> no match"
    );

    // Assign opls_154 to the oxygen: the H[O] match now succeeds and roots on H.
    let mut labels: HashMap<AtomId, String> = HashMap::new();
    labels.insert(o, "opls_154".to_string());
    let matches = pat.find_matches_with_labels(&g, &labels);
    assert_eq!(matches.len(), 1, "exactly the hydroxyl H matches");
    assert_eq!(
        matches[0][0], ho,
        "match roots on the hydroxyl H (query atom 0)"
    );

    // A different label on the oxygen must NOT satisfy `%opls_154`.
    let mut wrong: HashMap<AtomId, String> = HashMap::new();
    wrong.insert(o, "opls_155".to_string());
    assert!(
        pat.find_matches_with_labels(&g, &wrong).is_empty(),
        "wrong label -> no match"
    );
}

#[test]
fn test_context_label_legacy_find_matches_unaffected() {
    // ac-002: the legacy find_matches (no label context) is byte-for-byte
    // unaffected on non-%-patterns; a %-pattern simply never matches under it
    // (empty label context), never panics.
    let (g, _cm, _ch, _o, _ho) = ethanol();

    // Non-% pattern: identical result via both entries (empty labels).
    use std::collections::HashMap;
    let empty: HashMap<AtomId, String> = HashMap::new();
    let plain = SmartsPattern::parse("[O;X2]").unwrap();
    let legacy = plain.find_matches(&g);
    let with_empty = plain.find_matches_with_labels(&g, &empty);
    assert_eq!(legacy, with_empty, "empty-label path == legacy path");
    assert_eq!(legacy.len(), 1, "one hydroxyl oxygen");

    // A %-pattern under the legacy entry: empty context, so no match, no panic.
    let labeled = SmartsPattern::parse("[H][O;%opls_154]").unwrap();
    assert!(
        labeled.find_matches(&g).is_empty(),
        "legacy entry sees empty label context"
    );
}

#[test]
fn test_context_label_composes_with_other_primitives() {
    // ac-002: `%LABEL` composes inside an implicit/`;` AND chain — `[O;X2;%lbl]`
    // requires BOTH the degree-2 oxygen AND the label.
    use std::collections::HashMap;
    let (g, _cm, _ch, o, _ho) = ethanol();
    let pat = SmartsPattern::parse("[O;X2;%mylabel]").unwrap();

    let mut labels: HashMap<AtomId, String> = HashMap::new();
    labels.insert(o, "mylabel".to_string());
    let m = pat.find_matches_with_labels(&g, &labels);
    assert_eq!(m.len(), 1, "the labeled degree-2 O matches");
    assert_eq!(m[0][0], o);

    // Label present but on a wrong-degree atom would not match; here only O has
    // it, and O is X2, so the single match is correct. Remove the label -> none.
    let empty: HashMap<AtomId, String> = HashMap::new();
    assert!(pat.find_matches_with_labels(&g, &empty).is_empty());
}

// ── has_match consistent with find_matches ──────────────────────────────────

#[test]
fn test_has_match_consistency() {
    let fixtures = load_fixtures();
    let patterns: Vec<String> = fixtures["patterns"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    for name in fixtures["molecules"].as_object().unwrap().keys() {
        let (g, _) = build_mol(name, &fixtures);
        for p in &patterns {
            let pat = SmartsPattern::parse(p).unwrap();
            assert_eq!(
                pat.has_match(&g),
                !pat.find_matches(&g).is_empty(),
                "has_match disagrees with find_matches for {name} :: {p}"
            );
        }
    }
}
