//! Streaming trajectory readers for the WASM API.
//!
//! Implements Phase 1 / Task #4 of the streaming-trajectory spec
//! (see `molvis/docs/specs/streaming-trajectory.md`). Unlike the legacy
//! whole-content readers in [`super::reader`], these classes are designed
//! to be driven by a worker that owns:
//!
//! - a *reusable* WASM input buffer ([`allocInputBuffer`](
//!   `WasmLammpsDumpStream::alloc_input_buffer`)) into which the worker
//!   writes a chunk of the source (e.g. `blob.slice(start, end)`),
//! - a chunk-boundary-safe `FrameIndexBuilder` from `molrs-io` that emits
//!   [`FrameIndexEntry`] records as the source flows through it,
//! - a frame-by-frame parser that decodes a single byte range from the
//!   reusable buffer into a [`Frame`] held in
//!   `WasmLammpsDumpStream::output`.
//!
//! Five wasm classes share this exact shape — `WasmLammpsDumpStream`,
//! `WasmXyzStream`, `WasmPdbStream`, `WasmLammpsDataStream`,
//! `WasmSdfStream` — so they are generated by the
//! [`impl_wasm_traj_stream`] macro below. Each only differs in *which*
//! `FrameIndexBuilder` is constructed and *which* `parse_frame_bytes`
//! free function is invoked.
//!
//! # JS lifetime contract
//!
//! Every numeric pointer returned from this module (input buffer,
//! column data, grid array data) lives inside WASM linear memory.
//! `WebAssembly.Memory` may grow on any wasm-bindgen call, which
//! detaches the previous `ArrayBuffer`. Therefore **callers MUST
//! re-derive `new <Typed>Array(memory.buffer, ptr, len)` immediately
//! before each access and MUST NOT hold onto pointers across other
//! wasm calls.** The caller is also responsible for copying the data
//! into a JS-owned typed array before invoking [`parseRangeInInput`](
//! `WasmLammpsDumpStream::parse_range_in_input`) again.

use molrs::block::{Column, DType};
use molrs::frame::Frame as RsFrame;
use molrs_io::streaming::{FrameIndexBuilder, FrameIndexEntry as RsFrameIndexEntry};
use wasm_bindgen::prelude::*;

// Per-format builders + parsers. We re-import each format's
// `parse_frame_bytes` under a local alias so the macro can dispatch.
use molrs_io::lammps_data::{
    LammpsDataIndexBuilder, parse_frame_bytes as parse_lammps_data_frame_bytes,
};
use molrs_io::lammps_dump::{
    LammpsDumpIndexBuilder, parse_frame_bytes as parse_lammps_dump_frame_bytes,
};
use molrs_io::pdb::{PdbIndexBuilder, parse_frame_bytes as parse_pdb_frame_bytes};
use molrs_io::sdf::{SdfIndexBuilder, parse_frame_bytes as parse_sdf_frame_bytes};
use molrs_io::xyz::{XyzIndexBuilder, parse_frame_bytes as parse_xyz_frame_bytes};

// ---------------------------------------------------------------------------
// FrameIndexEntry exposed to JS
// ---------------------------------------------------------------------------

/// One frame's location inside the source byte stream.
///
/// `byteOffset` is the absolute byte position of the frame's first byte
/// inside the source (round-tripped through `f64`; the spec caps source
/// size at 1 TB which is well within `Number.MAX_SAFE_INTEGER`).
/// `byteLen` is `u32` — per-frame size never exceeds the worker chunk
/// size plus a small slack.
#[wasm_bindgen(js_name = FrameIndexEntry)]
#[derive(Debug, Clone, Copy)]
pub struct WasmFrameIndexEntry {
    byte_offset: f64,
    byte_len: u32,
}

#[wasm_bindgen(js_class = FrameIndexEntry)]
impl WasmFrameIndexEntry {
    /// Absolute byte offset of this frame inside the source (in bytes).
    #[wasm_bindgen(getter, js_name = byteOffset)]
    pub fn byte_offset(&self) -> f64 {
        self.byte_offset
    }

    /// Size of this frame's encoded byte range, in bytes.
    #[wasm_bindgen(getter, js_name = byteLen)]
    pub fn byte_len(&self) -> u32 {
        self.byte_len
    }
}

impl From<RsFrameIndexEntry> for WasmFrameIndexEntry {
    fn from(e: RsFrameIndexEntry) -> Self {
        // `byte_offset: u64 → f64` is exact for values ≤ 2^53; the
        // streaming protocol caps source size at 1 TB.
        Self {
            byte_offset: e.byte_offset as f64,
            byte_len: e.byte_len,
        }
    }
}

// ---------------------------------------------------------------------------
// Internal column / block enumeration helpers
// ---------------------------------------------------------------------------

/// Stable, sorted index into a parsed frame.
///
/// Block and column ordering inside `molrs::frame::Frame` come from
/// `HashMap`s, which means iteration order is non-deterministic. We
/// snapshot block keys (sorted) and per-block column keys (sorted) at
/// parse time so JS can address them by stable integer indices.
#[derive(Default)]
struct FrameIndex {
    blocks: Vec<BlockIndex>,
    grids: Vec<GridIndex>,
}

struct BlockIndex {
    name: String,
    columns: Vec<String>,
}

struct GridIndex {
    name: String,
    arrays: Vec<String>,
}

impl FrameIndex {
    fn new(frame: &RsFrame) -> Self {
        let mut blocks: Vec<BlockIndex> = frame
            .iter()
            .map(|(name, block)| {
                let mut columns: Vec<String> = block.keys().map(|k| k.to_string()).collect();
                columns.sort();
                BlockIndex {
                    name: name.to_string(),
                    columns,
                }
            })
            .collect();
        blocks.sort_by(|a, b| a.name.cmp(&b.name));

        let mut grids: Vec<GridIndex> = frame
            .grids()
            .map(|(name, grid)| {
                let mut arrays: Vec<String> = grid.keys().map(|k| k.to_string()).collect();
                arrays.sort();
                GridIndex {
                    name: name.to_string(),
                    arrays,
                }
            })
            .collect();
        grids.sort_by(|a, b| a.name.cmp(&b.name));

        Self { blocks, grids }
    }
}

/// Resolved view onto one column inside a parsed `Frame`.
struct ColumnAccess<'a> {
    column: &'a Column,
    name: &'a str,
}

fn column_access<'a>(
    frame: &'a RsFrame,
    index: &'a FrameIndex,
    block_idx: usize,
    col_idx: usize,
) -> Result<ColumnAccess<'a>, JsValue> {
    let block_meta = index.blocks.get(block_idx).ok_or_else(|| {
        JsValue::from_str(&format!("block index {} out of range", block_idx))
    })?;
    let col_name = block_meta.columns.get(col_idx).ok_or_else(|| {
        JsValue::from_str(&format!(
            "column index {} out of range in block {}",
            col_idx, block_meta.name
        ))
    })?;
    let block = frame
        .get(&block_meta.name)
        .ok_or_else(|| JsValue::from_str(&format!("block {} disappeared", block_meta.name)))?;
    let column = block
        .get(col_name)
        .ok_or_else(|| JsValue::from_str(&format!("column {} disappeared", col_name)))?;
    Ok(ColumnAccess {
        column,
        name: col_name.as_str(),
    })
}

fn dtype_str(dtype: DType) -> &'static str {
    match dtype {
        DType::Float => "f64",
        DType::Int => "i32",
        DType::UInt => "u32",
        DType::String => "string",
        // The five streaming formats only emit Float / Int / UInt / String
        // columns; bool / u8 are not produced by any current parser, but if
        // they show up we still report the underlying dtype so the JS side
        // can at least decide to skip the column rather than misinterpret it.
        DType::Bool => "bool",
        DType::U8 => "u8",
    }
}

fn column_total_len(column: &Column) -> usize {
    column.shape().iter().copied().product()
}

// ---------------------------------------------------------------------------
// Macro: generate per-format streaming class
// ---------------------------------------------------------------------------

/// Generate a per-format `Wasm*Stream` class.
///
/// Each invocation emits a `#[wasm_bindgen]` struct, a `#[wasm_bindgen]`
/// impl block, and the same set of JS-facing methods. The only thing that
/// varies between formats is the indexer constructor and the
/// `parse_frame_bytes` free function — both passed in as expressions.
macro_rules! impl_wasm_traj_stream {
    (
        struct_name = $struct:ident,
        js_name     = $js:ident,
        new_indexer = $new_indexer:expr,
        parse_fn    = $parse_fn:path,
    ) => {
        #[wasm_bindgen(js_name = $js)]
        pub struct $struct {
            indexer: Option<Box<dyn FrameIndexBuilder>>,
            input_buf: Vec<u8>,
            output: Option<RsFrame>,
            output_index: FrameIndex,
        }

        #[wasm_bindgen(js_class = $js)]
        impl $struct {
            /// Create a new streaming reader. The reusable input buffer
            /// starts empty; call [`allocInputBuffer`] before feeding data.
            #[wasm_bindgen(constructor)]
            #[allow(clippy::new_without_default)]
            pub fn new() -> Self {
                let indexer: Box<dyn FrameIndexBuilder> = Box::new($new_indexer);
                Self {
                    indexer: Some(indexer),
                    input_buf: Vec::new(),
                    output: None,
                    output_index: FrameIndex::default(),
                }
            }

            /// Resize the reusable input buffer so it can hold at least
            /// `len` bytes, and return the WASM linear-memory pointer to
            /// its first byte.
            ///
            /// CALLER MUST RE-DERIVE THIS POINTER AFTER ANY OTHER WASM CALL —
            /// `wasm.memory.buffer` may have been detached by a `memory.grow`.
            #[wasm_bindgen(js_name = allocInputBuffer)]
            pub fn alloc_input_buffer(&mut self, len: usize) -> *mut u8 {
                if self.input_buf.len() < len {
                    self.input_buf.resize(len, 0);
                }
                self.input_buf.as_mut_ptr()
            }

            /// Current capacity (in bytes) of the reusable input buffer.
            #[wasm_bindgen(js_name = inputCapacity)]
            pub fn input_capacity(&self) -> usize {
                self.input_buf.len()
            }

            /// Feed the first `len` bytes of the input buffer into the
            /// indexer at absolute source offset `globalOffset`. Returns
            /// any frame entries that became finalized as a result.
            ///
            /// `globalOffset` is round-tripped through `f64`; per the
            /// streaming protocol the source size is capped at 1 TB
            /// (well within `Number.MAX_SAFE_INTEGER`).
            #[wasm_bindgen(js_name = feedIndexChunk)]
            pub fn feed_index_chunk(
                &mut self,
                global_offset: f64,
                len: usize,
            ) -> Result<Vec<WasmFrameIndexEntry>, JsValue> {
                if global_offset < 0.0 || !global_offset.is_finite() {
                    return Err(JsValue::from_str(
                        "feedIndexChunk: globalOffset must be a non-negative finite number",
                    ));
                }
                if len > self.input_buf.len() {
                    return Err(JsValue::from_str(&format!(
                        "feedIndexChunk: len {} exceeds input buffer capacity {}",
                        len,
                        self.input_buf.len()
                    )));
                }
                let indexer = self
                    .indexer
                    .as_mut()
                    .ok_or_else(|| JsValue::from_str("feedIndexChunk: indexer already finished"))?;
                indexer.feed(&self.input_buf[..len], global_offset as u64);
                Ok(indexer.drain().into_iter().map(Into::into).collect())
            }

            /// Signal end-of-stream; return any trailing frame entry. The
            /// indexer is consumed and further `feedIndexChunk` calls
            /// throw.
            #[wasm_bindgen(js_name = finishIndex)]
            pub fn finish_index(&mut self) -> Result<Vec<WasmFrameIndexEntry>, JsValue> {
                let indexer = self
                    .indexer
                    .take()
                    .ok_or_else(|| JsValue::from_str("finishIndex: indexer already finished"))?;
                let trailing = indexer
                    .finish()
                    .map_err(|e| JsValue::from_str(&format!("finishIndex: {}", e)))?;
                Ok(trailing.into_iter().map(Into::into).collect())
            }

            /// Decode the byte range `[offset, offset + len)` from the
            /// reusable input buffer as a single frame. Replaces any
            /// previously cached output; the caller must extract data
            /// before the next `parseRangeInInput` (the same buffer can
            /// be overwritten in between).
            #[wasm_bindgen(js_name = parseRangeInInput)]
            pub fn parse_range_in_input(
                &mut self,
                offset: usize,
                len: usize,
            ) -> Result<(), JsValue> {
                let end = offset.checked_add(len).ok_or_else(|| {
                    JsValue::from_str("parseRangeInInput: offset + len overflowed usize")
                })?;
                if end > self.input_buf.len() {
                    return Err(JsValue::from_str(&format!(
                        "parseRangeInInput: range {}..{} exceeds input buffer length {}",
                        offset,
                        end,
                        self.input_buf.len()
                    )));
                }
                let bytes = &self.input_buf[offset..end];
                let frame = $parse_fn(bytes)
                    .map_err(|e| JsValue::from_str(&format!("parse error: {}", e)))?;
                self.output_index = FrameIndex::new(&frame);
                self.output = Some(frame);
                Ok(())
            }

            /// Drop the cached output frame, releasing its memory and
            /// invalidating any outstanding `columnPtr*` / `gridArrayPtr*`
            /// pointers. Subsequent extraction calls return 0 / empty
            /// until the next `parseRangeInInput`.
            #[wasm_bindgen(js_name = releaseFrame)]
            pub fn release_frame(&mut self) {
                self.output = None;
                self.output_index = FrameIndex::default();
            }

            // ---------- block / column metadata ----------

            /// Number of blocks in the most recently parsed frame.
            #[wasm_bindgen(js_name = blockCount)]
            pub fn block_count(&self) -> usize {
                self.output_index.blocks.len()
            }

            /// Name of block `blockIdx`, or empty string if out of range.
            #[wasm_bindgen(js_name = blockName)]
            pub fn block_name(&self, block_idx: usize) -> String {
                self.output_index
                    .blocks
                    .get(block_idx)
                    .map(|b| b.name.clone())
                    .unwrap_or_default()
            }

            /// Number of columns in block `blockIdx`.
            #[wasm_bindgen(js_name = columnCount)]
            pub fn column_count(&self, block_idx: usize) -> usize {
                self.output_index
                    .blocks
                    .get(block_idx)
                    .map(|b| b.columns.len())
                    .unwrap_or(0)
            }

            /// Column name at `(blockIdx, colIdx)`, or empty string if
            /// either index is out of range.
            #[wasm_bindgen(js_name = columnName)]
            pub fn column_name(&self, block_idx: usize, col_idx: usize) -> String {
                self.output_index
                    .blocks
                    .get(block_idx)
                    .and_then(|b| b.columns.get(col_idx))
                    .cloned()
                    .unwrap_or_default()
            }

            /// Column dtype string at `(blockIdx, colIdx)`. One of `"f64"`,
            /// `"u32"`, `"i32"`, `"string"` — or `"bool"` / `"u8"` if a
            /// future parser emits those (current streaming formats do not).
            /// Empty string if the index is out of range.
            #[wasm_bindgen(js_name = columnDtype)]
            pub fn column_dtype(&self, block_idx: usize, col_idx: usize) -> String {
                let Some(frame) = self.output.as_ref() else {
                    return String::new();
                };
                let Ok(access) = column_access(frame, &self.output_index, block_idx, col_idx)
                else {
                    return String::new();
                };
                dtype_str(access.column.dtype()).to_string()
            }

            /// Total flat element count of the column. For multi-dimensional
            /// columns (e.g. an Nx3 positions array) this is the product of
            /// all axes — i.e. the length of the slice the matching
            /// `columnPtr*` points at.
            #[wasm_bindgen(js_name = columnLen)]
            pub fn column_len(&self, block_idx: usize, col_idx: usize) -> usize {
                let Some(frame) = self.output.as_ref() else {
                    return 0;
                };
                let Ok(access) = column_access(frame, &self.output_index, block_idx, col_idx)
                else {
                    return 0;
                };
                column_total_len(access.column)
            }

            // ---------- numeric column pointers ----------
            //
            // CALLER MUST COPY the data into a JS-owned typed array before
            // any other wasm call: a subsequent allocInputBuffer / parse /
            // anything that triggers a `memory.grow` will detach
            // `wasm.memory.buffer`.

            /// Pointer to the contiguous `f64` slice backing this column,
            /// or 0 (null) if the column is missing or has the wrong
            /// dtype.
            ///
            /// **Lifetime**: valid only until the next non-trivial wasm
            /// call. See the module-level memory-grow contract.
            #[wasm_bindgen(js_name = columnPtrF64)]
            pub fn column_ptr_f64(&self, block_idx: usize, col_idx: usize) -> *const f64 {
                let Some(frame) = self.output.as_ref() else {
                    return std::ptr::null();
                };
                let Ok(access) = column_access(frame, &self.output_index, block_idx, col_idx)
                else {
                    return std::ptr::null();
                };
                let Some(arr) = access.column.as_float() else {
                    return std::ptr::null();
                };
                arr.as_slice_memory_order()
                    .map(|s| s.as_ptr())
                    .unwrap_or(std::ptr::null())
            }

            /// Pointer to the contiguous `u32` slice backing this column,
            /// or 0 (null) if the column is missing or has the wrong
            /// dtype.
            ///
            /// **Lifetime**: valid only until the next non-trivial wasm
            /// call. See the module-level memory-grow contract.
            #[wasm_bindgen(js_name = columnPtrU32)]
            pub fn column_ptr_u32(&self, block_idx: usize, col_idx: usize) -> *const u32 {
                let Some(frame) = self.output.as_ref() else {
                    return std::ptr::null();
                };
                let Ok(access) = column_access(frame, &self.output_index, block_idx, col_idx)
                else {
                    return std::ptr::null();
                };
                let Some(arr) = access.column.as_uint() else {
                    return std::ptr::null();
                };
                arr.as_slice_memory_order()
                    .map(|s| s.as_ptr())
                    .unwrap_or(std::ptr::null())
            }

            /// Pointer to the contiguous `i32` slice backing this column,
            /// or 0 (null) if the column is missing or has the wrong
            /// dtype.
            ///
            /// **Lifetime**: valid only until the next non-trivial wasm
            /// call. See the module-level memory-grow contract.
            #[wasm_bindgen(js_name = columnPtrI32)]
            pub fn column_ptr_i32(&self, block_idx: usize, col_idx: usize) -> *const i32 {
                let Some(frame) = self.output.as_ref() else {
                    return std::ptr::null();
                };
                let Ok(access) = column_access(frame, &self.output_index, block_idx, col_idx)
                else {
                    return std::ptr::null();
                };
                let Some(arr) = access.column.as_int() else {
                    return std::ptr::null();
                };
                arr.as_slice_memory_order()
                    .map(|s| s.as_ptr())
                    .unwrap_or(std::ptr::null())
            }

            /// Copy a string column out by value. Returns an empty array
            /// if the column is missing or not a string column.
            #[wasm_bindgen(js_name = columnStrings)]
            pub fn column_strings(&self, block_idx: usize, col_idx: usize) -> Vec<String> {
                let Some(frame) = self.output.as_ref() else {
                    return Vec::new();
                };
                let Ok(access) = column_access(frame, &self.output_index, block_idx, col_idx)
                else {
                    return Vec::new();
                };
                let Some(arr) = access.column.as_string() else {
                    return Vec::new();
                };
                let _ = access.name; // silence unused-name warning
                arr.iter().cloned().collect()
            }

            // ---------- simbox ----------

            /// Box H-matrix as a length-9 `Float64Array` (column-major:
            /// `[col0_x, col0_y, col0_z, col1_x, col1_y, col1_z, col2_x, col2_y, col2_z]`),
            /// or `undefined` if the frame has no simbox.
            ///
            /// Returned by VALUE — the typed array is owned by JS and is
            /// stable across subsequent wasm calls.
            #[wasm_bindgen(js_name = simboxH)]
            pub fn simbox_h(&self) -> Option<Vec<f64>> {
                let frame = self.output.as_ref()?;
                let sb = frame.simbox.as_ref()?;
                let h = sb.h_view();
                // Column-major flatten: H is stored as a 3x3 matrix where
                // h[[i, j]] is row i, column j. The wire format the spec
                // uses puts column 0 first.
                let mut out = Vec::with_capacity(9);
                for j in 0..3 {
                    for i in 0..3 {
                        out.push(h[[i, j]]);
                    }
                }
                Some(out)
            }

            /// Box origin as a length-3 `Float64Array`, or `undefined` if
            /// the frame has no simbox.
            #[wasm_bindgen(js_name = simboxOrigin)]
            pub fn simbox_origin(&self) -> Option<Vec<f64>> {
                let frame = self.output.as_ref()?;
                let sb = frame.simbox.as_ref()?;
                Some(sb.origin_view().iter().copied().collect())
            }

            /// Per-axis PBC flags as a length-3 `Uint8Array` (`1` = periodic,
            /// `0` = open), or `undefined` if the frame has no simbox.
            ///
            /// (wasm-bindgen does not support `[bool; 3]` returns natively,
            /// hence the `Uint8Array` wire format. The spec calls for
            /// `[boolean, boolean, boolean]`; the JS side is expected to
            /// `Boolean(arr[i])` each entry.)
            #[wasm_bindgen(js_name = simboxPbc)]
            pub fn simbox_pbc(&self) -> Option<Vec<u8>> {
                let frame = self.output.as_ref()?;
                let sb = frame.simbox.as_ref()?;
                let pbc = sb.pbc();
                Some(vec![pbc[0] as u8, pbc[1] as u8, pbc[2] as u8])
            }

            // ---------- grids ----------

            /// Number of named grids attached to the current frame.
            #[wasm_bindgen(js_name = gridCount)]
            pub fn grid_count(&self) -> usize {
                self.output_index.grids.len()
            }

            /// Name of grid `gridIdx`, or empty string if out of range.
            #[wasm_bindgen(js_name = gridName)]
            pub fn grid_name(&self, grid_idx: usize) -> String {
                self.output_index
                    .grids
                    .get(grid_idx)
                    .map(|g| g.name.clone())
                    .unwrap_or_default()
            }

            /// Grid dimensions `[nx, ny, nz]` as a length-3 `Uint32Array`.
            #[wasm_bindgen(js_name = gridShape)]
            pub fn grid_shape(&self, grid_idx: usize) -> Vec<u32> {
                let Some(frame) = self.output.as_ref() else {
                    return Vec::new();
                };
                let Some(meta) = self.output_index.grids.get(grid_idx) else {
                    return Vec::new();
                };
                let Some(grid) = frame.get_grid(&meta.name) else {
                    return Vec::new();
                };
                vec![grid.dim[0] as u32, grid.dim[1] as u32, grid.dim[2] as u32]
            }

            /// Grid origin (Cartesian, Å) as a length-3 `Float64Array`.
            #[wasm_bindgen(js_name = gridOrigin)]
            pub fn grid_origin(&self, grid_idx: usize) -> Vec<f64> {
                let Some(frame) = self.output.as_ref() else {
                    return Vec::new();
                };
                let Some(meta) = self.output_index.grids.get(grid_idx) else {
                    return Vec::new();
                };
                let Some(grid) = frame.get_grid(&meta.name) else {
                    return Vec::new();
                };
                grid.origin.to_vec()
            }

            /// Grid lattice cell as a length-9 `Float64Array` (column-major:
            /// `[col0_x, col0_y, col0_z, col1_x, col1_y, col1_z, col2_x, col2_y, col2_z]`).
            #[wasm_bindgen(js_name = gridCell)]
            pub fn grid_cell(&self, grid_idx: usize) -> Vec<f64> {
                let Some(frame) = self.output.as_ref() else {
                    return Vec::new();
                };
                let Some(meta) = self.output_index.grids.get(grid_idx) else {
                    return Vec::new();
                };
                let Some(grid) = frame.get_grid(&meta.name) else {
                    return Vec::new();
                };
                // `cell[i]` is column i; flatten column-major.
                let mut out = Vec::with_capacity(9);
                for col in 0..3 {
                    for row in 0..3 {
                        out.push(grid.cell[col][row]);
                    }
                }
                out
            }

            /// Grid PBC flags as a length-3 `Uint8Array` (`1` = periodic,
            /// `0` = open).
            #[wasm_bindgen(js_name = gridPbc)]
            pub fn grid_pbc(&self, grid_idx: usize) -> Vec<u8> {
                let Some(frame) = self.output.as_ref() else {
                    return Vec::new();
                };
                let Some(meta) = self.output_index.grids.get(grid_idx) else {
                    return Vec::new();
                };
                let Some(grid) = frame.get_grid(&meta.name) else {
                    return Vec::new();
                };
                vec![grid.pbc[0] as u8, grid.pbc[1] as u8, grid.pbc[2] as u8]
            }

            /// Number of named scalar arrays in grid `gridIdx`.
            #[wasm_bindgen(js_name = gridArrayCount)]
            pub fn grid_array_count(&self, grid_idx: usize) -> usize {
                self.output_index
                    .grids
                    .get(grid_idx)
                    .map(|g| g.arrays.len())
                    .unwrap_or(0)
            }

            /// Name of scalar array `(gridIdx, arrayIdx)`, or empty string
            /// if either index is out of range.
            #[wasm_bindgen(js_name = gridArrayName)]
            pub fn grid_array_name(&self, grid_idx: usize, array_idx: usize) -> String {
                self.output_index
                    .grids
                    .get(grid_idx)
                    .and_then(|g| g.arrays.get(array_idx))
                    .cloned()
                    .unwrap_or_default()
            }

            /// Pointer to the contiguous `f64` slice backing the grid
            /// scalar field, or 0 (null) if either index is out of range.
            ///
            /// **Lifetime**: valid only until the next non-trivial wasm
            /// call. See the module-level memory-grow contract.
            #[wasm_bindgen(js_name = gridArrayPtrF64)]
            pub fn grid_array_ptr_f64(
                &self,
                grid_idx: usize,
                array_idx: usize,
            ) -> *const f64 {
                let Some(frame) = self.output.as_ref() else {
                    return std::ptr::null();
                };
                let Some(meta) = self.output_index.grids.get(grid_idx) else {
                    return std::ptr::null();
                };
                let Some(name) = meta.arrays.get(array_idx) else {
                    return std::ptr::null();
                };
                let Some(grid) = frame.get_grid(&meta.name) else {
                    return std::ptr::null();
                };
                grid.get_raw(name)
                    .map(|s| s.as_ptr())
                    .unwrap_or(std::ptr::null())
            }

            /// Length (number of `f64` elements) of the grid scalar field.
            #[wasm_bindgen(js_name = gridArrayLen)]
            pub fn grid_array_len(&self, grid_idx: usize, array_idx: usize) -> usize {
                let Some(frame) = self.output.as_ref() else {
                    return 0;
                };
                let Some(meta) = self.output_index.grids.get(grid_idx) else {
                    return 0;
                };
                let Some(name) = meta.arrays.get(array_idx) else {
                    return 0;
                };
                let Some(grid) = frame.get_grid(&meta.name) else {
                    return 0;
                };
                grid.get_raw(name).map(|s| s.len()).unwrap_or(0)
            }
        }
    };
}

// ---------------------------------------------------------------------------
// Per-format instantiations
// ---------------------------------------------------------------------------

impl_wasm_traj_stream! {
    struct_name = WasmLammpsDumpStream,
    js_name     = WasmLammpsDumpStream,
    new_indexer = LammpsDumpIndexBuilder::new(),
    parse_fn    = parse_lammps_dump_frame_bytes,
}

impl_wasm_traj_stream! {
    struct_name = WasmXyzStream,
    js_name     = WasmXyzStream,
    new_indexer = XyzIndexBuilder::new(),
    parse_fn    = parse_xyz_frame_bytes,
}

impl_wasm_traj_stream! {
    struct_name = WasmPdbStream,
    js_name     = WasmPdbStream,
    new_indexer = PdbIndexBuilder::new(),
    parse_fn    = parse_pdb_frame_bytes,
}

impl_wasm_traj_stream! {
    struct_name = WasmLammpsDataStream,
    js_name     = WasmLammpsDataStream,
    new_indexer = LammpsDataIndexBuilder::new(),
    parse_fn    = parse_lammps_data_frame_bytes,
}

impl_wasm_traj_stream! {
    struct_name = WasmSdfStream,
    js_name     = WasmSdfStream,
    new_indexer = SdfIndexBuilder::new(),
    parse_fn    = parse_sdf_frame_bytes,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use wasm_bindgen_test::*;

    /// Two-frame LAMMPS dump (matches the smallest fixture in molrs-io tests).
    const LAMMPS_DUMP: &str = "ITEM: TIMESTEP\n0\n\
ITEM: NUMBER OF ATOMS\n2\n\
ITEM: BOX BOUNDS pp pp pp\n0 10\n0 10\n0 10\n\
ITEM: ATOMS id type x y z\n\
1 1 0.0 0.0 0.0\n\
2 1 1.0 1.0 1.0\n\
ITEM: TIMESTEP\n1\n\
ITEM: NUMBER OF ATOMS\n2\n\
ITEM: BOX BOUNDS pp pp pp\n0 10\n0 10\n0 10\n\
ITEM: ATOMS id type x y z\n\
1 1 0.5 0.5 0.5\n\
2 1 1.5 1.5 1.5\n";

    /// End-to-end smoke test for the LAMMPS dump streaming class:
    /// feed → finish → parse first frame → check block/column metadata.
    #[wasm_bindgen_test]
    fn lammps_dump_stream_indexes_and_parses_two_frames() {
        let mut stream = WasmLammpsDumpStream::new();
        let bytes = LAMMPS_DUMP.as_bytes();
        let cap = stream.alloc_input_buffer(bytes.len());
        assert!(!cap.is_null());
        // SAFETY: we just allocated this buffer at `len = bytes.len()`,
        // and we hold &mut self exclusively through this scope.
        unsafe {
            std::ptr::copy_nonoverlapping(bytes.as_ptr(), cap, bytes.len());
        }
        let entries = stream
            .feed_index_chunk(0.0, bytes.len())
            .expect("feed_index_chunk");
        let trailing = stream.finish_index().expect("finish_index");
        let mut all = entries;
        all.extend(trailing);
        assert_eq!(all.len(), 2, "expected exactly 2 frames in the fixture");

        // Decode frame 0 and check block/column metadata.
        let f0 = &all[0];
        stream
            .parse_range_in_input(f0.byte_offset() as usize, f0.byte_len() as usize)
            .expect("parse_range_in_input");
        assert_eq!(stream.block_count(), 1);
        assert_eq!(stream.block_name(0), "atoms");
        // atoms block has columns id (u32), type (i32), x, y, z (f64) — at least
        // some of them (columns are sorted alphabetically).
        let n_cols = stream.column_count(0);
        assert!(n_cols >= 5, "expected ≥5 columns, got {}", n_cols);
        // x column has 2 rows (matches NUMBER OF ATOMS).
        // We don't know the column index of "x" without scanning; do so.
        let mut x_idx = None;
        for i in 0..n_cols {
            if stream.column_name(0, i) == "x" {
                x_idx = Some(i);
                break;
            }
        }
        let x_idx = x_idx.expect("missing x column");
        assert_eq!(stream.column_dtype(0, x_idx), "f64");
        assert_eq!(stream.column_len(0, x_idx), 2);

        stream.release_frame();
        assert_eq!(stream.block_count(), 0);
    }

    /// Indexing the same fixture in many small chunks must produce the
    /// same entries as a single-shot feed.
    #[wasm_bindgen_test]
    fn lammps_dump_stream_chunked_index_matches_single_shot() {
        let bytes = LAMMPS_DUMP.as_bytes();

        // Single-shot.
        let mut s1 = WasmLammpsDumpStream::new();
        let p1 = s1.alloc_input_buffer(bytes.len());
        unsafe {
            std::ptr::copy_nonoverlapping(bytes.as_ptr(), p1, bytes.len());
        }
        let mut all1 = s1.feed_index_chunk(0.0, bytes.len()).expect("feed");
        all1.extend(s1.finish_index().expect("finish"));

        // 17-byte chunks — small enough to split lines, frames, and
        // ITEM headers across the boundary.
        let mut s2 = WasmLammpsDumpStream::new();
        let mut all2: Vec<WasmFrameIndexEntry> = Vec::new();
        let chunk_size = 17usize;
        let mut offset = 0usize;
        while offset < bytes.len() {
            let len = (bytes.len() - offset).min(chunk_size);
            let p = s2.alloc_input_buffer(len);
            unsafe {
                std::ptr::copy_nonoverlapping(bytes[offset..offset + len].as_ptr(), p, len);
            }
            let entries = s2.feed_index_chunk(offset as f64, len).expect("feed");
            all2.extend(entries);
            offset += len;
        }
        all2.extend(s2.finish_index().expect("finish"));

        assert_eq!(all1.len(), all2.len(), "frame count mismatch");
        for (a, b) in all1.iter().zip(all2.iter()) {
            assert_eq!(a.byte_offset(), b.byte_offset());
            assert_eq!(a.byte_len(), b.byte_len());
        }
    }

    /// Calling parse_range_in_input on an out-of-bounds range must error
    /// rather than panic.
    #[wasm_bindgen_test]
    fn parse_range_in_input_validates_bounds() {
        let mut stream = WasmLammpsDumpStream::new();
        stream.alloc_input_buffer(8);
        let res = stream.parse_range_in_input(4, 100);
        assert!(res.is_err(), "expected bounds error");
    }
}
