name: CI

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]
  workflow_dispatch:
  workflow_call:

jobs:
  rust:
    name: Rust
    uses: ./.github/workflows/ci-rust.yml

  wasm:
    name: WASM
    needs: rust
    uses: ./.github/workflows/ci-wasm.yml

  python:
    name: Python
    needs: rust
    uses: ./.github/workflows/ci-python.yml

  capi:
    name: C API
    needs: rust
    uses: ./.github/workflows/ci-capi.yml
